--==========================================================================================================================
-- MINORCIVILIZATIONS
--==========================================================================================================================
-- MinorCivilization_JFD_CultureTypes
-------------------------------------	
CREATE TABLE IF NOT EXISTS 
MinorCivilization_JFD_CultureTypes(
	MinorCivilizationType 						text 	REFERENCES MinorCivilizations(Type) 	default NULL,
	CultureType 								text											default NULL);

INSERT INTO MinorCivilization_JFD_CultureTypes
		(MinorCivilizationType,				CultureType)
VALUES	('MINOR_CIV_SUK_NAQADA',			'CULTURE_JFD_MESOPOTAMIC'),	
		('MINOR_CIV_SUK_BRATISLAVA',		'CULTURE_JFD_CENTRAL'),
		('MINOR_CIV_SUK_BOLOGNA',			'CULTURE_JFD_SOUTHERN'),
		('MINOR_CIV_SUK_ABOMEY',			'CULTURE_JFD_WEST_AFRICAN'),
		('MINOR_CIV_SUK_SICAN',				'CULTURE_JFD_ANDEAN'),
		('MINOR_CIV_SUK_URBINO',			'CULTURE_JFD_SOUTHERN'),
		('MINOR_CIV_SUK_PALMYRA',			'CULTURE_JFD_CLASSICAL'),
		('MINOR_CIV_SUK_LWOW',				'CULTURE_JFD_CENTRAL'),
		('MINOR_CIV_SUK_NAN_MADOL',			'CULTURE_JFD_OCEANIC'),
		('MINOR_CIV_SUK_SAN_JOSE',			'CULTURE_JFD_COLONIAL'),
		('MINOR_CIV_SUK_SOBA',				'CULTURE_JFD_SEMITIC'),
		('MINOR_CIV_SUK_MONACO',			'CULTURE_JFD_WESTERN'),
		('MINOR_CIV_SUK_ULM',				'CULTURE_JFD_CENTRAL'),
		('MINOR_CIV_SUK_AVA',				'CULTURE_JFD_MANDALA'),

		('MINOR_CIV_SUK_SYRACUSE',			'CULTURE_JFD_CLASSICAL'),
		('MINOR_CIV_SUK_MESA_VERDE',		'CULTURE_JFD_WOODLANDS'),
		('MINOR_CIV_SUK_VIJAYA',			'CULTURE_JFD_MANDALA'),
		('MINOR_CIV_SUK_ANTANANARIVO',		'CULTURE_JFD_OCEANIC'),
		('MINOR_CIV_SUK_REVAL',				'CULTURE_JFD_CENTRAL'),
		('MINOR_CIV_SUK_SAN_JUAN',			'CULTURE_JFD_COLONIAL'),
		('MINOR_CIV_SUK_ISANAPURA',			'CULTURE_JFD_MANDALA'),
		('MINOR_CIV_SUK_NOK',				'CULTURE_JFD_WEST_AFRICAN'),
		('MINOR_CIV_SUK_RIGA',				'CULTURE_JFD_CENTRAL'),
		('MINOR_CIV_SUK_BONGA',				'CULTURE_JFD_SEMITIC'),
		('MINOR_CIV_SUK_CATALHOYUK',		'CULTURE_JFD_MESOPOTAMIC'),
		('MINOR_CIV_SUK_SNAKETOWN',			'CULTURE_JFD_WOODLANDS'),
		('MINOR_CIV_SUK_KUK',				'CULTURE_JFD_OCEANIC'),
		('MINOR_CIV_SUK_KATSINA',			'CULTURE_JFD_WEST_AFRICAN'),

		('MINOR_CIV_SUK_MOGADISHU',			'CULTURE_JFD_ISLAMIC'),
		('MINOR_CIV_SUK_MARIEHAMN',			'CULTURE_JFD_CENTRAL'),
		('MINOR_CIV_SUK_DORPAT',			'CULTURE_JFD_CENTRAL'),
		('MINOR_CIV_SUK_ANURADHAPURA',		'CULTURE_JFD_BHARATA'),
		('MINOR_CIV_SUK_GADIR',				'CULTURE_JFD_SEMITIC'),
		('MINOR_CIV_SUK_HONG_KONG',			'CULTURE_JFD_ORIENTAL'),
		('MINOR_CIV_SUK_MALACCA',			'CULTURE_JFD_EAST_INDIES'),
		('MINOR_CIV_SUK_OYO_ILE',			'CULTURE_JFD_WEST_AFRICAN'),
		('MINOR_CIV_SUK_SAMARKAND',			'CULTURE_JFD_STEPPE'),
		('MINOR_CIV_SUK_ORMUS',				'CULTURE_JFD_IRANIAN'),		
		('MINOR_CIV_SUK_SINGAPORE',			'CULTURE_JFD_ORIENTAL'),
		('MINOR_CIV_SUK_ADEN',				'CULTURE_JFD_ISLAMIC'),
		('MINOR_CIV_SUK_MANICA',			'CULTURE_JFD_BANTU'),
		('MINOR_CIV_SUK_LUBECK',			'CULTURE_JFD_CENTRAL'),

		('MINOR_CIV_SUK_HOLMGARD',			'CULTURE_JFD_NORTHERN'),
		('MINOR_CIV_SUK_SOKOTO',			'CULTURE_JFD_WEST_AFRICAN'),
		('MINOR_CIV_SUK_JERICHO',			'CULTURE_JFD_MESOPOTAMIC'),
		('MINOR_CIV_SUK_DALI',				'CULTURE_JFD_ORIENTAL'),
		('MINOR_CIV_SUK_TLAXCALA',			'CULTURE_JFD_MESOAMERICAN'),
		('MINOR_CIV_SUK_GIBRALTAR',			'CULTURE_JFD_WESTERN'),
		('MINOR_CIV_SUK_PSKOV',				'CULTURE_JFD_EASTERN'),
		('MINOR_CIV_SUK_VALLETTA',			'CULTURE_JFD_SOUTHERN'),

		('MINOR_CIV_SUK_LINDISFARNE',		'CULTURE_JFD_WESTERN'),
		('MINOR_CIV_SUK_IFE',				'CULTURE_JFD_WEST_AFRICAN'),
		('MINOR_CIV_SUK_JERUSALEM',			'CULTURE_JFD_SEMITIC'),
		('MINOR_CIV_SUK_UKONSAARI',			'CULTURE_JFD_POLAR'),
		('MINOR_CIV_SUK_GOBEKLI_TEPE',		'CULTURE_JFD_MESOPOTAMIC'),
		('MINOR_CIV_SUK_VARANASI',			'CULTURE_JFD_BHARATA'),
		('MINOR_CIV_SUK_AVIGNON',			'CULTURE_JFD_WESTERN'),
		('MINOR_CIV_SUK_WITTENBERG',		'CULTURE_JFD_CENTRAL');
------------------------
-- MinorCivilization_JFD_CultureTypes
------------------------
CREATE TABLE IF NOT EXISTS 
	MinorCivilization_JFD_Titles (
	MinorCivilizationType					text	REFERENCES MinorCivilizations(Type)				default NULL,
	ReligionType							text	REFERENCES Religions(Type)						default NULL,
	UniqueGovernmentTitle					text													default NULL,
	UniqueLeaderTitle						text													default NULL);

INSERT INTO MinorCivilization_JFD_Titles
			(MinorCivilizationType,				UniqueGovernmentTitle,											UniqueLeaderTitle)
SELECT		Type,								'TXT_KEY_GOVERNMENT_JFD_TITLE_' || Type,						'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_' || Type
FROM MinorCivilizations;
------------------------
-- Language_en_US
------------------------
INSERT OR REPLACE INTO Language_en_US (Tag, Text)
VALUES 
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_ABOMEY',
		'Kingdom of Abomey'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_ABOMEY',
		'King'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_ABOMEY_FEMININE',
		'Queen'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_AVA',
		'Kingdom of Ava'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_AVA',
		'King'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_AVA_FEMININE',
		'Queen'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_BOLOGNA',
		'Commune of Bologna'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_BOLOGNA',
		'Gonfaloniere'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_BOLOGNA_FEMININE',
		'Gonfaloniere'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_BRATISLAVA',
		'Principality of Bratislava'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_BRATISLAVA',
		'Prince'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_BRATISLAVA_FEMININE',
		'Prince'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_SAN_JOSE',
		'Republic of San José'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_SAN_JOSE',
		'President'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_SAN_JOSE_FEMININE',
		'President'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_LWOW',
		'Principality of Lwów'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_LWOW',
		'Prince'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_LWOW_FEMININE',
		'Prince'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_MONACO',
		'Principality of Monaco'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_MONACO',
		'Prince'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_MONACO_FEMININE',
		'Prince'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_NAN_MADOL',
		'Kingdom of Nan Madol'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_NAN_MADOL',
		'Saudeleur'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_NAN_MADOL_FEMININE',
		'Saudeleur'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_PALMYRA',
		'Kingdom of Palmyra'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_PALMYRA',
		'King'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_PALMYRA_FEMININE',
		'Queen'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_NAQADA',
		'Kingdom of Naqada'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_NAQADA',
		'Nswt-bity'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_NAQADA_FEMININE',
		'Nswt-bity'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_SICAN',
		'Kingdom of Sicán'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_SICAN',
		'King'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_SICAN_FEMININE',
		'Queen'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_SOBA',
		'Kingdom of Soba'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_SOBA',
		'King'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_SOBA_FEMININE',
		'Queen'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_ULM',
		'Free City of Ulm'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_ULM',
		'Bürgermeister'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_ULM_FEMININE',
		'Bürgermeister'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_URBINO',
		'Duchy of Urbino'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_URBINO',
		'Duke'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_URBINO_FEMININE',
		'Duchess'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_ANTANANARIVO',
		'Kingdom of Antananarivo'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_ANTANANARIVO',
		'King'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_ANTANANARIVO_FEMININE',
		'Queen'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_BONGA',
		'Kingdom of Bonga'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_BONGA',
		'King'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_BONGA_FEMININE',
		'Queen'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_CATALHOYUK',
		'Chiefdom of Çatalhöyük'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_CATALHOYUK',
		'Chief'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_CATALHOYUK_FEMININE',
		'Chieftess'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_KUK',
		'Kuk Chiefdom'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_KUK',
		'Chief'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_KUK_FEMININE',
		'Chieftess'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_MESA_VERDE',
		'Pueblo of Mesa Verde'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_MESA_VERDE',
		'Chief'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_MESA_VERDE_FEMININE',
		'Chief'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_NOK',
		'Nok Chiefdom'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_NOK',
		'Chief'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_NOK_FEMININE',
		'Chieftess'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_ORMUS',
		'Kingdom of Ormus'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_ORMUS',
		'King'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_ORMUS_FEMININE',
		'Queen'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_ISANAPURA',
		'Kingdom of Isanapura'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_ISANAPURA',
		'King'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_ISANAPURA_FEMININE',
		'Queen'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_REVAL',
		'Free City of Reval'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_REVAL',
		'Bürgermeister'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_REVAL_FEMININE',
		'Bürgermeister'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_RIGA',
		'Bishopric of Riga'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_RIGA',
		'Bishop'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_RIGA_FEMININE',
		'Bishop'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_SAN_JUAN',
		'Republic of San Juan'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_SAN_JUAN',
		'President'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_SAN_JUAN_FEMININE',
		'President'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_SNAKETOWN',
		'Chiefdom of Snaketown'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_SNAKETOWN',
		'Chief'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_SNAKETOWN_FEMININE',
		'Chieftess'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_SYRACUSE',
		'Polis of Syracuse'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_SYRACUSE',
		'Tyrant'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_SYRACUSE_FEMININE',
		'Tyrant'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_VIJAYA',
		'Kingdom of Vijaya'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_VIJAYA',
		'King'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_VIJAYA_FEMININE',
		'Queen'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_ADEN',
		'Sultanate of Aden'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_ADEN',
		'Sultan'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_ADEN_FEMININE',
		'Sultana'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_ANURADHAPURA',
		'Kingdom of Anuradhapura'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_ANURADHAPURA',
		'King'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_ANURADHAPURA_FEMININE',
		'Queen'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_KATSINA',
		'Emirate of Katsina'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_KATSINA',
		'Emir'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_KATSINA_FEMININE',
		'Emira'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_DORPAT',
		'Bishopric of Dorpat'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_DORPAT',
		'Bishop'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_DORPAT_FEMININE',
		'Bishop'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_GADIR',
		'Colony of Gadir'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_GADIR',
		'King'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_GADIR_FEMININE',
		'Queen'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_HONG_KONG',
		'Republic of Hong Kong'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_HONG_KONG',
		'President'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_HONG_KONG_FEMININE',
		'President'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_LUBECK',
		'Free City of Lübeck'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_LUBECK',
		'Bürgermeister'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_LUBECK_FEMININE',
		'Bürgermeister'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_MALACCA',
		'Sultanate of Malacca'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_MALACCA',
		'Sultan'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_MALACCA_FEMININE',
		'Sultana'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_MANICA',
		'Kingdom of Manica'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_MANICA',
		'Mwene'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_MANICA_FEMININE',
		'Mwene'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_MARIEHAMN',
		'Republic of Mariehamn'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_MARIEHAMN',
		'Premier'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_MARIEHAMN_FEMININE',
		'Premier'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_MOGADISHU',
		'Sultanate of Mogadishu'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_MOGADISHU',
		'Sultan'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_MOGADISHU_FEMININE',
		'Sultana'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_OYO_ILE',
		'Kingdom of Oyo-Ile'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_OYO_ILE',
		'Alaafin'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_OYO_ILE_FEMININE',
		'Alaafin'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_SAMARKAND',
		'Hakimdom of Samarkand'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_SAMARKAND',
		'Hakim'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_SAMARKAND_FEMININE',
		'Hakim'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_SINGAPORE',
		'Republic of Singapore'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_SINGAPORE',
		'President'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_SINGAPORE_FEMININE',
		'President'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_DALI',
		'Kingdom of Dali'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_DALI',
		'King'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_DALI_FEMININE',
		'Queen'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_GIBRALTAR',
		'Kingdom of Gibraltar'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_GIBRALTAR',
		'King'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_GIBRALTAR_FEMININE',
		'Queen'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_HOLMGARD',
		'Chiefdom of Holmgård'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_HOLMGARD',
		'Chief'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_HOLMGARD_FEMININE',
		'Chief'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_JERICHO',
		'Kingdom of Jericho'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_JERICHO',
		'King'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_JERICHO_FEMININE',
		'Queen'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_PSKOV',
		'Republic of Pskov'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_PSKOV',
		'Posadnik'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_PSKOV_FEMININE',
		'Posadnika'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_SOKOTO',
		'Caliphate of Sokoto'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_SOKOTO',
		'Caliph'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_SOKOTO_FEMININE',
		'Calipha'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_TLAXCALA',
		'Altepetl of Tlaxcala'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_TLAXCALA',
		'Tlatoani'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_TLAXCALA_FEMININE',
		'Cihuatlahtoani'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_VALLETTA',
		'Republic of Valetta'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_VALLETTA',
		'Grandmaster'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_VALLETTA_FEMININE',
		'Grandmaster'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_AVIGNON',
		'Avignon'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_AVIGNON',
		'Sovereign'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_AVIGNON_FEMININE',
		'Sovereign'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_GOBEKLI_TEPE',
		'Chiefdom of Göbekli Tepe'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_GOBEKLI_TEPE',
		'Chief'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_GOBEKLI_TEPE_FEMININE',
		'Chieftess'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_IFE',
		'Ile-Ife'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_IFE',
		'Ooni'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_IFE_FEMININE',
		'Ooni'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_JERUSALEM',
		'Kingdom of Jerusalem'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_JERUSALEM',
		'King'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_JERUSALEM_FEMININE',
		'Queen'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_UKONSAARI',
		'Siejdi of Ukonsaari'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_UKONSAARI',
		'Noaidi'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_UKONSAARI_FEMININE',
		'Noaidi'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_LINDISFARNE',
		'Bishopric of Lindisfarne'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_LINDISFARNE',
		'Bishop'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_LINDISFARNE_FEMININE',
		'Bishop'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_VARANASI',
		'Kingdom of Varanasi'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_VARANASI',
		'Maharaja'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_VARANASI_FEMININE',
		'Maharani'
	),	
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_MINOR_CIV_SUK_WITTENBERG',
		'Duchy of Wittenberg'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_WITTENBERG',
		'Duke'
	),
	(
		'TXT_KEY_GOVERNMENT_JFD_TITLE_LEADER_MINOR_CIV_SUK_WITTENBERG_FEMININE',
		'Duchess'
	);
--==========================================================================================================================		
--==========================================================================================================================