	--==========================================================================================================================
-- MINOR CIVILIZATIONS
--==========================================================================================================================
-- MinorCivilizations
--------------------------------------------------------------------------------------------------------------------------
DELETE FROM MinorCivilizations;
INSERT INTO MinorCivilizations 	
		(Type, 								ArtStyleType,				ArtStyleSuffix,		ArtStylePrefix,			MinorCivTrait,					DefaultPlayerColor)
VALUES	('MINOR_CIV_SUK_NAQADA',			'ARTSTYLE_MIDDLE_EAST',		'_AFRI',			'AFRICAN ',				'MINOR_TRAIT_CULTURED',			'PLAYERCOLOR_MINOR_MIDDLE_PURPLE'),
		('MINOR_CIV_SUK_BRATISLAVA',		'ARTSTYLE_EUROPEAN',		'_EURO',			'EUROPEAN ',			'MINOR_TRAIT_CULTURED',			'PLAYERCOLOR_MINOR_WHITE'),
		('MINOR_CIV_SUK_BOLOGNA',			'ARTSTYLE_GRECO_ROMAN',		'_MED',				'MEDITERRANEAN ',		'MINOR_TRAIT_CULTURED',			'PLAYERCOLOR_MINOR_LIGHT_GREEN'),
		('MINOR_CIV_SUK_ABOMEY',			'ARTSTYLE_MIDDLE_EAST',		'_AFRI',			'AFRICAN ',				'MINOR_TRAIT_CULTURED',			'PLAYERCOLOR_MINOR_LIGHT_BLUE'),
		('MINOR_CIV_SUK_SICAN',				'ARTSTYLE_SOUTH_AMERICA',	'_AMER',			'AMERICAN ',			'MINOR_TRAIT_CULTURED',			'PLAYERCOLOR_MINOR_YELLOW'),
		('MINOR_CIV_SUK_URBINO',			'ARTSTYLE_GRECO_ROMAN',		'_MED',				'MEDITERRANEAN ',		'MINOR_TRAIT_CULTURED',			'PLAYERCOLOR_MINOR_CYAN'),
		('MINOR_CIV_SUK_PALMYRA',			'ARTSTYLE_GRECO_ROMAN',		'_ASIA',			'ASIAN',				'MINOR_TRAIT_CULTURED',			'PLAYERCOLOR_MINOR_BLUE'),
		('MINOR_CIV_SUK_LWOW',				'ARTSTYLE_EUROPEAN',		'_EURO',			'EUROPEAN ',			'MINOR_TRAIT_CULTURED',			'PLAYERCOLOR_MINOR_PEACH'),
		('MINOR_CIV_SUK_NAN_MADOL',			'ARTSTYLE_POLYNESIAN',		'_MED',				'MEDITERRANEAN ',		'MINOR_TRAIT_CULTURED',			'PLAYERCOLOR_MINOR_MIDDLE_CYAN'),
		('MINOR_CIV_SUK_SAN_JOSE',			'ARTSTYLE_GRECO_ROMAN',		'_ASIA',			'ASIAN',				'MINOR_TRAIT_CULTURED',			'PLAYERCOLOR_MINOR_LIGHT_PURPLE'),
		('MINOR_CIV_SUK_SOBA',				'ARTSTYLE_MIDDLE_EAST',		'_AFRI',			'AFRICAN ',				'MINOR_TRAIT_CULTURED',			'PLAYERCOLOR_MINOR_GREEN'),
		('MINOR_CIV_SUK_MONACO',			'ARTSTYLE_GRECO_ROMAN',		'_MED',				'MEDITERRANEAN ',		'MINOR_TRAIT_CULTURED',			'PLAYERCOLOR_MINOR_PURPLE'),
		('MINOR_CIV_SUK_ULM',				'ARTSTYLE_EUROPEAN',		'_EURO',			'EUROPEAN ',			'MINOR_TRAIT_CULTURED',			'PLAYERCOLOR_MINOR_LIGHT_ORANGE'),
		('MINOR_CIV_SUK_AVA',				'ARTSTYLE_ASIAN',			'_ASIA',			'ASIAN',				'MINOR_TRAIT_CULTURED',			'PLAYERCOLOR_MINOR_LIGHT_YELLOW'),

		('MINOR_CIV_SUK_SYRACUSE',			'ARTSTYLE_GRECO_ROMAN',		'_MED',				'MEDITERRANEAN ',		'MINOR_TRAIT_MARITIME',			'PLAYERCOLOR_MINOR_MIDDLE_BLUE'),
		('MINOR_CIV_SUK_MESA_VERDE',		'ARTSTYLE_SOUTH_AMERICA',	'_AMER',			'AMERICAN ',			'MINOR_TRAIT_MARITIME',			'PLAYERCOLOR_MINOR_BLUE'),
		('MINOR_CIV_SUK_VIJAYA',			'ARTSTYLE_ASIAN',			'_ASIA',			'ASIAN',				'MINOR_TRAIT_MARITIME',			'PLAYERCOLOR_MINOR_LIGHT_YELLOW'),
		('MINOR_CIV_SUK_ANTANANARIVO',		'ARTSTYLE_POLYNESIAN',		'_AFRI',			'AFRICAN ',				'MINOR_TRAIT_MARITIME',			'PLAYERCOLOR_MINOR_LIGHT_ORANGE'),
		('MINOR_CIV_SUK_REVAL',				'ARTSTYLE_EUROPEAN',		'_EURO',			'EUROPEAN ',			'MINOR_TRAIT_MARITIME',			'PLAYERCOLOR_MINOR_PURPLE'),
		('MINOR_CIV_SUK_KATSINA',			'ARTSTYLE_MIDDLE_EAST',		'_AFRI',			'AFRICAN ',				'MINOR_TRAIT_MARITIME',			'PLAYERCOLOR_MINOR_GRAY'),		
		('MINOR_CIV_SUK_SAN_JUAN',			'ARTSTYLE_GRECO_ROMAN',		'_AMER',			'AMERICAN ',			'MINOR_TRAIT_MARITIME',			'PLAYERCOLOR_MINOR_LIGHT_GREEN'),
		('MINOR_CIV_SUK_ISANAPURA',			'ARTSTYLE_ASIAN',			'_ASIA',			'ASIAN ',				'MINOR_TRAIT_MARITIME',			'PLAYERCOLOR_MINOR_GREEN'),
		('MINOR_CIV_SUK_NOK',				'ARTSTYLE_MIDDLE_EAST',		'_AFRI',			'AFRICAN ',				'MINOR_TRAIT_MARITIME',			'PLAYERCOLOR_MINOR_MIDDLE_CYAN'),
		('MINOR_CIV_SUK_RIGA',				'ARTSTYLE_EUROPEAN',		'_EURO',			'EUROPEAN ',			'MINOR_TRAIT_MARITIME',			'PLAYERCOLOR_MINOR_CYAN'),
		('MINOR_CIV_SUK_BONGA',				'ARTSTYLE_MIDDLE_EAST',		'_AFRI',			'AFRICAN ',				'MINOR_TRAIT_MARITIME',			'PLAYERCOLOR_MINOR_LIGHT_PURPLE'),
		('MINOR_CIV_SUK_CATALHOYUK',		'ARTSTYLE_MIDDLE_EAST',		'_ASIA',			'ASIAN',				'MINOR_TRAIT_MARITIME',			'PLAYERCOLOR_MINOR_PEACH'),
		('MINOR_CIV_SUK_SNAKETOWN',			'ARTSTYLE_SOUTH_AMERICA',	'_AMER',			'AMERICAN ',			'MINOR_TRAIT_MARITIME',			'PLAYERCOLOR_MINOR_YELLOW'),
		('MINOR_CIV_SUK_KUK',				'ARTSTYLE_POLYNESIAN',		'_ASIA',			'ASIAN',				'MINOR_TRAIT_MARITIME',			'PLAYERCOLOR_MINOR_WHITE'),

		('MINOR_CIV_SUK_MOGADISHU',			'ARTSTYLE_MIDDLE_EAST',		'_AFRI',			'AFRICAN ',				'MINOR_TRAIT_MERCANTILE',		'PLAYERCOLOR_MINOR_PEACH'),
		('MINOR_CIV_SUK_MARIEHAMN',			'ARTSTYLE_EUROPEAN',		'_EURO',			'EUROPEAN ',			'MINOR_TRAIT_MERCANTILE',		'PLAYERCOLOR_MINOR_GREEN'),
		('MINOR_CIV_SUK_DORPAT',			'ARTSTYLE_EUROPEAN',		'_EURO',			'EUROPEAN ',			'MINOR_TRAIT_MERCANTILE',		'PLAYERCOLOR_MINOR_WHITE'),
		('MINOR_CIV_SUK_ANURADHAPURA',		'ARTSTYLE_ASIAN',			'_ASIA',			'ASIAN ',				'MINOR_TRAIT_MERCANTILE',		'PLAYERCOLOR_MINOR_LIGHT_PURPLE'),
		('MINOR_CIV_SUK_GADIR',				'ARTSTYLE_GRECO_ROMAN',		'_MED',				'MEDITERRANEAN ',		'MINOR_TRAIT_MERCANTILE',		'PLAYERCOLOR_MINOR_MIDDLE_CYAN'),
		('MINOR_CIV_SUK_HONG_KONG',			'ARTSTYLE_ASIAN',			'_ASIA',			'ASIAN ',				'MINOR_TRAIT_MERCANTILE',		'PLAYERCOLOR_MINOR_BLUE'),
		('MINOR_CIV_SUK_MALACCA',			'ARTSTYLE_ASIAN',			'_ASIA',			'ASIAN ',				'MINOR_TRAIT_MERCANTILE',		'PLAYERCOLOR_MINOR_CYAN'),
		('MINOR_CIV_SUK_OYO_ILE',			'ARTSTYLE_MIDDLE_EAST',		'_AFRI',			'AFRICAN ',				'MINOR_TRAIT_MERCANTILE',		'PLAYERCOLOR_MINOR_PURPLE'),
		('MINOR_CIV_SUK_SAMARKAND',			'ARTSTYLE_MIDDLE_EAST',		'_ASIA',			'ASIAN ',				'MINOR_TRAIT_MERCANTILE',		'PLAYERCOLOR_MINOR_MIDDLE_BLUE'),
		('MINOR_CIV_SUK_SINGAPORE',			'ARTSTYLE_ASIAN',			'_ASIA',			'ASIAN ',				'MINOR_TRAIT_MERCANTILE',		'PLAYERCOLOR_MINOR_LIGHT_YELLOW'),
		('MINOR_CIV_SUK_ADEN',				'ARTSTYLE_MIDDLE_EAST',		'_ASIA',			'ASIAN ',				'MINOR_TRAIT_MERCANTILE',		'PLAYERCOLOR_MINOR_LIGHT_BLUE'),
		('MINOR_CIV_SUK_ORMUS',				'ARTSTYLE_MIDDLE_EAST',		'_ASIA',			'ASIAN',				'MINOR_TRAIT_MERCANTILE',		'PLAYERCOLOR_MINOR_GRAY'),
		('MINOR_CIV_SUK_MANICA',			'ARTSTYLE_MIDDLE_EAST',		'_AFRI',			'AFRICAN ',				'MINOR_TRAIT_MERCANTILE',		'PLAYERCOLOR_MINOR_MIDDLE_PURPLE'),
		('MINOR_CIV_SUK_LUBECK',			'ARTSTYLE_EUROPEAN',		'_EURO',			'EUROPEAN ',			'MINOR_TRAIT_MERCANTILE',		'PLAYERCOLOR_MINOR_YELLOW'),

		('MINOR_CIV_SUK_HOLMGARD',			'ARTSTYLE_EUROPEAN',		'_EURO',			'EUROPEAN ',			'MINOR_TRAIT_MILITARISTIC',		'PLAYERCOLOR_MINOR_GRAY'),
		('MINOR_CIV_SUK_SOKOTO',			'ARTSTYLE_MIDDLE_EAST',		'_AFRI',			'AFRICAN ',				'MINOR_TRAIT_MILITARISTIC',		'PLAYERCOLOR_MINOR_GREEN'),
		('MINOR_CIV_SUK_JERICHO',			'ARTSTYLE_GRECO_ROMAN',		'_ASIA',			'ASIAN ',				'MINOR_TRAIT_MILITARISTIC',		'PLAYERCOLOR_MINOR_LIGHT_ORANGE'),
		('MINOR_CIV_SUK_DALI',				'ARTSTYLE_ASIAN',			'_ASIA',			'ASIAN ',				'MINOR_TRAIT_MILITARISTIC',		'PLAYERCOLOR_MINOR_CYAN'),
		('MINOR_CIV_SUK_TLAXCALA',			'ARTSTYLE_SOUTH_AMERICA',	'_AMER',			'AMERICAN ',			'MINOR_TRAIT_MILITARISTIC',		'PLAYERCOLOR_MINOR_LIGHT_PURPLE'),
		('MINOR_CIV_SUK_GIBRALTAR',			'ARTSTYLE_EUROPEAN',		'_MED',				'MEDITERRANEAN ',		'MINOR_TRAIT_MILITARISTIC',		'PLAYERCOLOR_MINOR_MIDDLE_PURPLE'),
		('MINOR_CIV_SUK_PSKOV',				'ARTSTYLE_EUROPEAN',		'_EURO',			'EUROPEAN ',			'MINOR_TRAIT_MILITARISTIC',		'PLAYERCOLOR_MINOR_LIGHT_GREEN'),
		('MINOR_CIV_SUK_VALLETTA',			'ARTSTYLE_GRECO_ROMAN',		'_MED',				'MEDITERRANEAN ',		'MINOR_TRAIT_MILITARISTIC',		'PLAYERCOLOR_MINOR_YELLOW'),

		('MINOR_CIV_SUK_LINDISFARNE',		'ARTSTYLE_EUROPEAN',		'_EURO',			'EUROPEAN ',			'MINOR_TRAIT_RELIGIOUS',		'PLAYERCOLOR_MINOR_MIDDLE_BLUE'),
		('MINOR_CIV_SUK_IFE',				'ARTSTYLE_MIDDLE_EAST',		'_AFRI',			'AFRICAN ',				'MINOR_TRAIT_RELIGIOUS',		'PLAYERCOLOR_MINOR_GRAY'),
		('MINOR_CIV_SUK_JERUSALEM',			'ARTSTYLE_MIDDLE_EAST',		'_ASIA',			'ASIAN ',				'MINOR_TRAIT_RELIGIOUS',		'PLAYERCOLOR_MINOR_WHITE'),
		('MINOR_CIV_SUK_UKONSAARI',			'ARTSTYLE_ASIAN',			'_ASIA',			'ASIAN ',				'MINOR_TRAIT_RELIGIOUS',		'PLAYERCOLOR_MINOR_MIDDLE_PURPLE'),
		('MINOR_CIV_SUK_GOBEKLI_TEPE',		'ARTSTYLE_MIDDLE_EAST',		'_ASIA',			'ASIAN ',				'MINOR_TRAIT_RELIGIOUS',		'PLAYERCOLOR_MINOR_CYAN'),
		('MINOR_CIV_SUK_VARANASI',			'ARTSTYLE_ASIAN',			'_ASIA',			'ASIAN ',				'MINOR_TRAIT_RELIGIOUS',		'PLAYERCOLOR_MINOR_LIGHT_GREEN'),
		('MINOR_CIV_SUK_AVIGNON',			'ARTSTYLE_EUROPEAN',		'_EURO',			'EUROPEAN ',			'MINOR_TRAIT_RELIGIOUS',		'PLAYERCOLOR_MINOR_LIGHT_YELLOW'),
		('MINOR_CIV_SUK_WITTENBERG',		'ARTSTYLE_EUROPEAN',		'_EURO',			'EUROPEAN ',			'MINOR_TRAIT_RELIGIOUS',		'PLAYERCOLOR_MINOR_LIGHT_PURPLE');

DELETE FROM MinorCivilizations WHERE Type NOT IN (
	'MINOR_CIV_SUK_AVIGNON',
	'MINOR_CIV_SUK_WITTENBERG',
	'MINOR_CIV_SUK_IFE',
	'MINOR_CIV_SUK_VARANASI',	
	'MINOR_CIV_SUK_UKONSAARI',
	'MINOR_CIV_SUK_GOBEKLI_TEPE',
	'MINOR_CIV_SUK_JERUSALEM',
	'MINOR_CIV_SUK_LINDISFARNE',

	'MINOR_CIV_SUK_TLAXCALA',
	'MINOR_CIV_SUK_HOLMGARD',
	'MINOR_CIV_SUK_PSKOV',	
	'MINOR_CIV_SUK_DALI',
	'MINOR_CIV_SUK_VALLETTA',	
	'MINOR_CIV_SUK_SOKOTO',	
	'MINOR_CIV_SUK_JERICHO',	
	'MINOR_CIV_SUK_GIBRALTAR',		

	'MINOR_CIV_SUK_SINGAPORE',	
	'MINOR_CIV_SUK_MARIEHAMN',	
	'MINOR_CIV_SUK_GADIR',
	'MINOR_CIV_SUK_LUBECK',	
	'MINOR_CIV_SUK_OYO_ILE',
	'MINOR_CIV_SUK_SAMARKAND',
	'MINOR_CIV_SUK_ANURADHAPURA',
	'MINOR_CIV_SUK_MANICA',
	'MINOR_CIV_SUK_HONG_KONG',
	'MINOR_CIV_SUK_ORMUS',

	'MINOR_CIV_SUK_KUK',
	'MINOR_CIV_SUK_REVAL',
	'MINOR_CIV_SUK_MESA_VERDE',
	'MINOR_CIV_SUK_SYRACUSE',
	'MINOR_CIV_SUK_CATALHOYUK',
	'MINOR_CIV_SUK_SAN_JUAN',
	'MINOR_CIV_SUK_SNAKETOWN',
	'MINOR_CIV_SUK_NOK',
	'MINOR_CIV_SUK_ISANAPURA',
	'MINOR_CIV_SUK_VIJAYA',

	'MINOR_CIV_SUK_URBINO',
	'MINOR_CIV_SUK_NAQADA',
	'MINOR_CIV_SUK_ABOMEY',
	'MINOR_CIV_SUK_SAN_JOSE',
	'MINOR_CIV_SUK_ULM',
	'MINOR_CIV_SUK_BOLOGNA',
	'MINOR_CIV_SUK_AVA',
	'MINOR_CIV_SUK_SICAN',
	'MINOR_CIV_SUK_PALMYRA',
	'MINOR_CIV_SUK_NAN_MADOL'						
);

UPDATE MinorCivilizations SET Description = 'TXT_KEY_' || Type;
UPDATE MinorCivilizations SET 
	ShortDescription	= Description,
	Civilopedia			= Description || '_PEDIA',
	Adjective			= Description || '_ADJ';

UPDATE MinorCivilizations
SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_CULTURED'
WHERE MinorCivTrait = 'MINOR_TRAIT_CULTURED';

UPDATE MinorCivilizations
SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_MARITIME'
WHERE MinorCivTrait = 'MINOR_TRAIT_MARITIME';

UPDATE MinorCivilizations
SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_MERCANTILE'
WHERE MinorCivTrait = 'MINOR_TRAIT_MERCANTILE';

UPDATE MinorCivilizations
SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_MILITARISTIC'
WHERE MinorCivTrait = 'MINOR_TRAIT_MILITARISTIC';

UPDATE MinorCivilizations
SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_RELIGIOUS'
WHERE MinorCivTrait = 'MINOR_TRAIT_RELIGIOUS';
--------------------------------------------------------------------------------------------------------------------------
-- MinorCivilization_CityNames
--------------------------------------------------------------------------------------------------------------------------
DELETE FROM MinorCivilization_CityNames;
INSERT INTO MinorCivilization_CityNames
		(MinorCivType,		CityName)
SELECT	Type,				Description
FROM MinorCivilizations;
--------------------------------------------------------------------------------------------------------------------------
-- MinorCivilization_Flavors
--------------------------------------------------------------------------------------------------------------------------
DELETE FROM MinorCivilization_Flavors;

INSERT INTO MinorCivilization_Flavors
		(MinorCivType,		FlavorType,				Flavor)
SELECT	Type,				'FLAVOR_EXPANSION',		0
FROM MinorCivilizations;

INSERT INTO MinorCivilization_Flavors
		(MinorCivType,		FlavorType,				Flavor)
SELECT	Type,				'FLAVOR_NUKE',			0
FROM MinorCivilizations;

INSERT INTO MinorCivilization_Flavors
		(MinorCivType,		FlavorType,				Flavor)
SELECT	Type,				'FLAVOR_WONDER',		0
FROM MinorCivilizations;

----------------

INSERT INTO MinorCivilization_Flavors
		(MinorCivType,		FlavorType,						Flavor)
SELECT	Type,				'FLAVOR_CULTURE',				10
FROM MinorCivilizations WHERE MinorCivTrait = 'MINOR_TRAIT_CULTURED';

INSERT INTO MinorCivilization_Flavors
		(MinorCivType,		FlavorType,						Flavor)
SELECT	Type,				'FLAVOR_GROWTH',				10
FROM MinorCivilizations WHERE MinorCivTrait = 'MINOR_TRAIT_MARITIME';

INSERT INTO MinorCivilization_Flavors
		(MinorCivType,		FlavorType,						Flavor)
SELECT	Type,				'FLAVOR_GOLD',					10
FROM MinorCivilizations WHERE MinorCivTrait = 'MINOR_TRAIT_MERCANTILE';

INSERT INTO MinorCivilization_Flavors
		(MinorCivType,		FlavorType,						Flavor)
SELECT	Type,				'FLAVOR_CITY_DEFENSE',			7
FROM MinorCivilizations WHERE MinorCivTrait = 'MINOR_TRAIT_MILITARISTIC';

INSERT INTO MinorCivilization_Flavors
		(MinorCivType,		FlavorType,						Flavor)
SELECT	Type,				'FLAVOR_DEFENSE',				7
FROM MinorCivilizations WHERE MinorCivTrait = 'MINOR_TRAIT_MILITARISTIC';

INSERT INTO MinorCivilization_Flavors
		(MinorCivType,		FlavorType,						Flavor)
SELECT	Type,				'FLAVOR_OFFENSE',				7
FROM MinorCivilizations WHERE MinorCivTrait = 'MINOR_TRAIT_MILITARISTIC';

INSERT INTO MinorCivilization_Flavors
		(MinorCivType,		FlavorType,						Flavor)
SELECT	Type,				'FLAVOR_MILITARY_TRAINING',		7
FROM MinorCivilizations WHERE MinorCivTrait = 'MINOR_TRAIT_MILITARISTIC';

INSERT INTO MinorCivilization_Flavors
		(MinorCivType,		FlavorType,						Flavor)
SELECT	Type,				'FLAVOR_RELIGION',				10
FROM MinorCivilizations WHERE MinorCivTrait = 'MINOR_TRAIT_RELIGIOUS';
--==========================================================================================================================
--==========================================================================================================================