--==========================================================================================================================
-- AUDIO
--==========================================================================================================================	
-- Audio_Sounds
------------------------------	
INSERT INTO Audio_Sounds 
		(SoundID, 									Filename, 								LoadType)
VALUES	('SND_EVENT_JFD_EARTHQUAKE_01', 			'Event_Earthquake01',					'DynamicResident'),
		('SND_EVENT_JFD_FANFARE_01', 				'Event_Fanfare01',						'DynamicResident'),
		('SND_EVENT_JFD_GENERIC_01', 				'Event_Generic01',						'DynamicResident'),
		('SND_EVENT_CHOICE_JFD_DEFAULT', 			'EventChoice_Default',					'DynamicResident'),
			
		('SND_EVENT_JFD_ANDEAN', 					'Andean',								'DynamicResident'),
		('SND_EVENT_JFD_ASSEMBLY', 					'Assembly',								'DynamicResident'),
		('SND_EVENT_JFD_ASSEMBLY_BAD', 				'AssemblyBad',							'DynamicResident'),
		('SND_EVENT_JFD_BANTU', 					'Bantu',								'DynamicResident'),
		('SND_EVENT_JFD_BEAST', 					'Beast',								'DynamicResident'),
		('SND_EVENT_JFD_BEAST_FAIL', 				'BeastFail',							'DynamicResident'),
		('SND_EVENT_JFD_BEAST_SUIT', 				'BeastSuit',							'DynamicResident'),
		('SND_EVENT_JFD_BHARATA', 					'Bharata',								'DynamicResident'),
		('SND_EVENT_JFD_BIRTH', 					'Birth',								'DynamicResident'),
		('SND_EVENT_JFD_CALL_TO_ARMS', 				'CallToArms',							'DynamicResident'),
		('SND_EVENT_JFD_CHURCH_BELLS', 				'ChurchBells',							'DynamicResident'),
		('SND_EVENT_JFD_CROWD_CHEER', 				'CrowdCheer',							'DynamicResident'),
		('SND_EVENT_JFD_DECLARE_WAR', 				'DeclareWar',							'DynamicResident'),
		('SND_EVENT_JFD_DISBANDED', 				'Disbanded',							'DynamicResident'),
		('SND_EVENT_JFD_DIPLOMACY', 				'Diplomacy',							'DynamicResident'),
		('SND_EVENT_JFD_DIPLOMACY_BAD', 			'DiplomacyBad',							'DynamicResident'),
		('SND_EVENT_JFD_DUNGEON',	 				'Jail',									'DynamicResident'),
		('SND_EVENT_JFD_EVENT', 					'Event',								'DynamicResident'),
		('SND_EVENT_JFD_FANFARE_HEAVY', 			'FanfareHeavy',							'DynamicResident'),
		('SND_EVENT_JFD_FANFARE_LIGHT', 			'FanfareLight',							'DynamicResident'),
		('SND_EVENT_JFD_GARDEN', 					'Garden',								'DynamicResident'),
		('SND_EVENT_JFD_GENERIC_EVENT_BAD', 		'GenericEventBad',						'DynamicResident'),
		('SND_EVENT_JFD_GENERIC_EVENT_BAD_2', 		'GenericEventBad2',						'DynamicResident'),
		('SND_EVENT_JFD_GENERIC_EVENT_BAD_3', 		'GenericEventBad3',						'DynamicResident'),
		('SND_EVENT_JFD_GOLD_GIFT', 				'GoldGift',								'DynamicResident'),
		('SND_EVENT_JFD_HORSE_WHINY', 				'HorseWhiny',							'DynamicResident'),
		('SND_EVENT_JFD_HUNTING', 					'Hunting',								'DynamicResident'),
		('SND_EVENT_JFD_INSANE', 					'InsaneLaugh',							'DynamicResident'),
		('SND_EVENT_JFD_INSANE_HORSE', 				'InsaneLaughHorse',						'DynamicResident'),
		('SND_EVENT_JFD_JOUSTING', 					'CircusMaximus',						'DynamicResident'),
		('SND_EVENT_JFD_JOUSTING_INSANE', 			'JoustingInsane',						'DynamicResident'),
		('SND_EVENT_JFD_KATUJE', 					'Katuje',								'DynamicResident'),
		('SND_EVENT_JFD_LEVIES', 					'Levies',								'DynamicResident'),
		('SND_EVENT_JFD_MANDALA', 					'Mandala',								'DynamicResident'),
		('SND_EVENT_JFD_MESOAMERICAN', 				'Mesoamerican',							'DynamicResident'),
		('SND_EVENT_JFD_MILITARY', 					'Military',								'DynamicResident'),
		('SND_EVENT_JFD_NORTHERN', 					'Northern',								'DynamicResident'),
		('SND_EVENT_JFD_OCEANIC', 					'Oceanic',								'DynamicResident'),
		('SND_EVENT_JFD_PAPAL', 					'Papal',								'DynamicResident'),
		('SND_EVENT_JFD_REBELS', 					'Rebels',								'DynamicResident'),
		('SND_EVENT_JFD_SAHUL', 					'Sahul',								'DynamicResident'),
		('SND_EVENT_JFD_SICK_DEATH', 				'SickDeath',							'DynamicResident'),
		('SND_EVENT_JFD_SYNOD', 					'Synod',								'DynamicResident'),
		('SND_EVENT_JFD_TECH_INVEST', 				'TechInvest',							'DynamicResident'),
		('SND_EVENT_JFD_TIRELESS', 					'Tireless',								'DynamicResident'),
		('SND_EVENT_JFD_TRIBAL_AMERICAN', 			'TribalAmerican',						'DynamicResident'),
		('SND_EVENT_JFD_WHISPERS', 					'Whispers',								'DynamicResident'),
		('SND_EVENT_JFD_WRITING', 					'Writing',								'DynamicResident');	
------------------------------
-- Audio_2DSounds
------------------------------	
INSERT INTO Audio_2DSounds 
		(ScriptID, 									SoundID, 								SoundType, 				DontTriggerDuplicates,	DontPlayMoreThan,	TaperSoundtrackVolume,	MinVolume, 	MaxVolume)
VALUES	('AS2D_EVENT_JFD_EARTHQUAKE_01',			'SND_EVENT_JFD_EARTHQUAKE_01',			'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_FANFARE_01',				'SND_EVENT_JFD_FANFARE_01',				'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_GENERIC_01',				'SND_EVENT_JFD_GENERIC_01',				'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_CHOICE_JFD_DEFAULT',			'SND_EVENT_CHOICE_JFD_DEFAULT',			'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		
		('AS2D_EVENT_JFD_ANDEAN',					'SND_EVENT_JFD_ANDEAN',					'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_ASSEMBLY',					'SND_EVENT_JFD_ASSEMBLY',				'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_ASSEMBLY_BAD',				'SND_EVENT_JFD_ASSEMBLY_BAD',			'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_BALL',						'SND_BUILDING_JFD_MANOR',				'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_BANTU',					'SND_EVENT_JFD_BANTU',					'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_BEAST',					'SND_EVENT_JFD_BEAST',					'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_BEAST_FAIL',				'SND_EVENT_JFD_BEAST_FAIL',				'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_BEAST_SUIT',				'SND_EVENT_JFD_BEAST_SUIT',				'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_BHARATA',					'SND_EVENT_JFD_BHARATA',				'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_BIRTH',					'SND_EVENT_JFD_BIRTH',					'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_CALL_TO_ARMS',				'SND_EVENT_JFD_CALL_TO_ARMS',			'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_CHURCH_BELLS',				'SND_EVENT_JFD_CHURCH_BELLS',			'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_CROWD_CHEER',				'SND_EVENT_JFD_CROWD_CHEER',			'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_DECLARE_WAR',				'SND_EVENT_JFD_DECLARE_WAR',			'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_DIPLOMACY',				'SND_EVENT_JFD_DIPLOMACY',				'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_DIPLOMACY_BAD',			'SND_EVENT_JFD_DIPLOMACY_BAD',			'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_DISBANDED',				'SND_EVENT_JFD_DISBANDED',				'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_DUNGEON',					'SND_EVENT_JFD_DUNGEON',				'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_EVENT',					'SND_EVENT_JFD_EVENT',					'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_FAIL',						'SND_EVENT_JFD_FAIL',					'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_FANFARE_HEAVY',			'SND_EVENT_JFD_FANFARE_HEAVY',			'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_FANFARE_LIGHT',			'SND_EVENT_JFD_FANFARE_LIGHT',			'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_GARDEN',					'SND_EVENT_JFD_GARDEN',					'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_GENERIC_EVENT_BAD',		'SND_EVENT_JFD_GENERIC_EVENT_BAD',		'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_GENERIC_EVENT_BAD_2',		'SND_EVENT_JFD_GENERIC_EVENT_BAD_2',	'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_GENERIC_EVENT_BAD_3',		'SND_EVENT_JFD_GENERIC_EVENT_BAD_3',	'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_GOLD_GIFT',				'SND_EVENT_JFD_GOLD_GIFT',				'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_HORSE_WHINY',				'SND_EVENT_JFD_HORSE_WHINY',			'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_HUNTING',					'SND_EVENT_JFD_HUNTING',				'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_INSANE',					'SND_EVENT_JFD_INSANE',					'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_INSANE_HORSE',				'SND_EVENT_JFD_INSANE_HORSE',			'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_JOUSTING',					'SND_EVENT_JFD_JOUSTING',				'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_JOUSTING_INSANE',			'SND_EVENT_JFD_JOUSTING_INSANE',		'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_KATUJE',					'SND_EVENT_JFD_KATUJE',					'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_LEVIES',					'SND_EVENT_JFD_LEVIES',					'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_MANDALA',					'SND_EVENT_JFD_MANDALA',				'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_MESOAMERICAN',				'SND_EVENT_JFD_MESOAMERICAN',			'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_MILITARY',					'SND_EVENT_JFD_MILITARY',				'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_NORTHERN',					'SND_EVENT_JFD_NORTHERN',				'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_OCEANIC',					'SND_EVENT_JFD_OCEANIC',				'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_PAPAL',					'SND_EVENT_JFD_PAPAL',					'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_REBELS',					'SND_EVENT_JFD_REBELS',					'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_SAHUL',					'SND_EVENT_JFD_SAHUL',					'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_SICK_DEATH',				'SND_EVENT_JFD_SICK_DEATH',				'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_SYNOD',					'SND_EVENT_JFD_SYNOD',					'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_TECH_INVEST',				'SND_EVENT_JFD_TECH_INVEST',			'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_TIRELESS',					'SND_EVENT_JFD_TIRELESS',				'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_TRIBAL_AMERICAN',			'SND_EVENT_JFD_TRIBAL_AMERICAN',		'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_WHISPERS',					'SND_EVENT_JFD_WHISPERS',				'GAME_SFX', 			1,						1,					0.0,					100, 		100),
		('AS2D_EVENT_JFD_WRITING',					'SND_EVENT_JFD_WRITING',				'GAME_SFX', 			1,						1,					0.0,					60, 		60);
--==========================================================================================================================
--==========================================================================================================================