--==========================================================================================================================
-- ICON ATLASES
--==========================================================================================================================
-- IconTextureAtlases
--------------------------------------------------------------------------------------------------------------------------	
INSERT INTO IconTextureAtlases 
		(Atlas, 									IconSize, 	Filename, 													IconsPerRow, 	IconsPerColumn)
VALUES	('JFD_PIETY_BELIEF_ATLAS', 					256, 		'JFD_PietyBeliefAtlas_256.dds',								7, 				2),
		('JFD_PIETY_BELIEF_ATLAS', 					128, 		'JFD_PietyBeliefAtlas_128.dds',								7, 				2),
		('JFD_PIETY_BELIEF_ATLAS', 					80, 		'JFD_PietyBeliefAtlas_80.dds',								7, 				2),
		('JFD_PIETY_BELIEF_ATLAS', 					64, 		'JFD_PietyBeliefAtlas_64.dds',								7, 				2),
		('JFD_PIETY_BELIEF_ATLAS', 					45, 		'JFD_PietyBeliefAtlas_45.dds',								7, 				2),
		('JFD_PIETY_BUILDING_ATLAS', 				256, 		'JFD_PietyBuildingAtlas_256.dds',							3, 				2),
		('JFD_PIETY_BUILDING_ATLAS', 				128, 		'JFD_PietyBuildingAtlas_128.dds',							3, 				2),
		('JFD_PIETY_BUILDING_ATLAS', 				80, 		'JFD_PietyBuildingAtlas_80.dds',							3, 				2),
		('JFD_PIETY_BUILDING_ATLAS', 				64, 		'JFD_PietyBuildingAtlas_64.dds',							3, 				2),
		('JFD_PIETY_BUILDING_ATLAS', 				45, 		'JFD_PietyBuildingAtlas_45.dds',							3, 				2),
		('JFD_PIETY_MISSION_ATLAS', 				64, 		'JFD_PietyMissionAtlas_64.dds',								1, 				1),
		('JFD_PIETY_MISSION_ATLAS', 				45, 		'JFD_PietyMissionAtlas_45.dds',								1, 				1),
		('JFD_PIETY_HERESY_ATLAS',					128, 		'JFD_PietyHeresyAtlas_128.dds',								8, 				1),
		('JFD_PIETY_HERESY_ATLAS',					80, 		'JFD_PietyHeresyAtlas_80.dds',								8, 				1),
		('JFD_PIETY_HERESY_ATLAS',					64, 		'JFD_PietyHeresyAtlas_64.dds',								8, 				1),
		('JFD_PIETY_HERESY_ATLAS',					48, 		'JFD_PietyHeresyAtlas_48.dds',								8, 				1),
		('JFD_PIETY_HERESY_ATLAS',					45, 		'JFD_PietyHeresyAtlas_45.dds',								8, 				1),
		('JFD_PIETY_HERESY_ATLAS',					32, 		'JFD_PietyHeresyAtlas_32.dds',								8, 				1),
		('JFD_PIETY_HERESY_ATLAS',					24, 		'JFD_PietyHeresyAtlas_24.dds',								8, 				1),
		('JFD_PIETY_HERESY_ATLAS',					16, 		'JFD_PietyHeresyAtlas_16.dds',								8, 				1),
		('JFD_PIETY_PROCESS_ATLAS', 				256, 		'JFD_PietyProcessAtlas_256.dds',							1, 				1),
		('JFD_PIETY_PROCESS_ATLAS', 				128, 		'JFD_PietyProcessAtlas_128.dds',							1, 				1),
		('JFD_PIETY_PROCESS_ATLAS', 				80, 		'JFD_PietyProcessAtlas_80.dds',								1, 				1),
		('JFD_PIETY_PROCESS_ATLAS', 				64, 		'JFD_PietyProcessAtlas_64.dds',								1, 				1),
		('JFD_PIETY_PROCESS_ATLAS', 				45, 		'JFD_PietyProcessAtlas_45.dds',								1, 				1),
		('JFD_PIETY_RELIGION_ATLAS',				128, 		'JFD_PietyReligionAtlas_128.dds',							1, 				1),
		('JFD_PIETY_RELIGION_ATLAS',				80, 		'JFD_PietyReligionAtlas_80.dds',							1, 				1),
		('JFD_PIETY_RELIGION_ATLAS',				64, 		'JFD_PietyReligionAtlas_64.dds',							1, 				1),
		('JFD_PIETY_RELIGION_ATLAS',				48, 		'JFD_PietyReligionAtlas_48.dds',							1, 				1),
		('JFD_PIETY_RELIGION_ATLAS',				45, 		'JFD_PietyReligionAtlas_45.dds',							1, 				1),
		('JFD_PIETY_RELIGION_ATLAS',				32, 		'JFD_PietyReligionAtlas_32.dds',							1, 				1),
		('JFD_PIETY_RELIGION_ATLAS',				24, 		'JFD_PietyReligionAtlas_24.dds',							1, 				1),
		('JFD_PIETY_RELIGION_ATLAS',				16, 		'JFD_PietyReligionAtlas_16.dds',							1, 				1),
		('JFD_PIETY_RESOURCE_ATLAS', 				256, 		'JFD_PietyResourceAtlas_256.dds',							1, 				1),
		('JFD_PIETY_RESOURCE_ATLAS', 				128, 		'JFD_PietyResourceAtlas_128.dds',							1, 				1),
		('JFD_PIETY_RESOURCE_ATLAS', 				80, 		'JFD_PietyResourceAtlas_80.dds',							1, 				1),
		('JFD_PIETY_RESOURCE_ATLAS', 				64, 		'JFD_PietyResourceAtlas_64.dds',							1, 				1),
		('JFD_PIETY_RESOURCE_ATLAS', 				45, 		'JFD_PietyResourceAtlas_45.dds',							1, 				1),
		('JFD_PIETY_NOTIFICATION_ATLAS',			80, 		'JFD_PietyNotificationAtlas_80.dds',						1, 				1),
		('JFD_PIETY_SPECIALIST_ATLAS',				256, 		'JFD_PietySpecialistAtlas_256.dds',							1, 				2),
		('JFD_PIETY_SPECIALIST_ATLAS',				128, 		'JFD_PietySpecialistAtlas_128.dds',							1, 				2),
		('JFD_PIETY_SPECIALIST_ATLAS',				80, 		'JFD_PietySpecialistAtlas_80.dds',							1, 				2),
		('JFD_PIETY_SPECIALIST_ATLAS',				64, 		'JFD_PietySpecialistAtlas_64.dds',							1, 				2),
		('JFD_PIETY_SPECIALIST_ATLAS',				45, 		'JFD_PietySpecialistAtlas_45.dds',							1, 				2),
		('JFD_PIETY_SPECIALIST_ATLAS',				32, 		'JFD_PietySpecialistAtlas_32.dds',							1, 				2),
		('JFD_PIETY_TECH_ATLAS',					256, 		'JFD_PietyTechAtlas_256.dds',								2, 				2),
		('JFD_PIETY_TECH_ATLAS',					214, 		'JFD_PietyTechAtlas_214.dds',								2, 				2),
		('JFD_PIETY_TECH_ATLAS',					128, 		'JFD_PietyTechAtlas_128.dds',								2, 				2),
		('JFD_PIETY_TECH_ATLAS',					80, 		'JFD_PietyTechAtlas_80.dds',								2, 				2),
		('JFD_PIETY_TECH_ATLAS',					64, 		'JFD_PietyTechAtlas_64.dds',								2, 				2),
		('JFD_PIETY_TECH_ATLAS',					45, 		'JFD_PietyTechAtlas_45.dds',								2, 				2),
		('JFD_PIETY_VICTORY_ATLAS',					128, 		'JFD_PietyVictoryAtlas_128.dds',							1, 				1),
		('JFD_PIETY_WONDER_ATLAS', 					256, 		'JFD_PietyWonderAtlas_256.dds',								3, 				3),
		('JFD_PIETY_WONDER_ATLAS', 					128, 		'JFD_PietyWonderAtlas_128.dds',								3, 				3),
		('JFD_PIETY_WONDER_ATLAS', 					80, 		'JFD_PietyWonderAtlas_80.dds',								3, 				3),
		('JFD_PIETY_WONDER_ATLAS', 					64, 		'JFD_PietyWonderAtlas_64.dds',								3, 				3),
		('JFD_PIETY_WONDER_ATLAS', 					45, 		'JFD_PietyWonderAtlas_45.dds',								3, 				3);
--==========================================================================================================================
--==========================================================================================================================