--==========================================================================================================================
-- GREAT PERSONS
--==========================================================================================================================
-- GreatPersons
--------------------------------------------------------------------------------------------------------------------------	
UPDATE GreatPersons SET Specialist = 'SPECIALIST_JFD_MONK' WHERE Type = 'GREATPERSON_PROPHET'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_RTP_PIETY_SPECIALIST_ADDITIONS_MONK' AND Value = 1);
--==========================================================================================================================
-- UNIT CLASSES
--==========================================================================================================================
-- UnitClass_Missions
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO UnitClass_Missions 	
		(UnitClassType, 		MissionType)
SELECT	'UNITCLASS_PROPHET', 	'MISSION_JFD_CLERICS'
WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'SUK_DECISIONS_RTP_PIETY_RESOURCE_ADDITIONS_CLERICS' AND Value = 1);

INSERT INTO UnitClass_Missions 	
		(UnitClassType, 		MissionType)
SELECT	'UNITCLASS_PROPHET', 	'MISSION_JFD_START_REFORMATION'
WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_RTP_PIETY_CORE' AND Value = 1);
--==========================================================================================================================
-- UNITS
--==========================================================================================================================
-- Units
-----------------------------------------------------------------------------------------------------	
UPDATE Units SET GPExtra = 4 WHERE Type = 'UNIT_PROPHET';

UPDATE Units
SET SpreadReligion = 0, ReligiousStrength = 0, ReligionSpreads = 0
WHERE Class = 'UNITCLASS_PROPHET'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_RTP_PIETY_GREAT_PEOPLE_CHANGES_PROPHET' AND Value = 1);
-----------------------------------------------------------------------------------------------------
-- Unit_AITypes
-----------------------------------------------------------------------------------------------------	
INSERT INTO Unit_AITypes
		(UnitType,				UnitAIType)
SELECT	'UNIT_PROPHET',			'UNITAI_ARTIST'
WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_RTP_PIETY_GREAT_PROPHET_ARTIFACTS' AND Value = 1);
-----------------------------------------------------------------------------------------------------
-- Unit_UniqueNames
-----------------------------------------------------------------------------------------------------	
DELETE FROM Unit_UniqueNames WHERE UnitType = 'UNIT_PROPHET';
INSERT INTO Unit_UniqueNames
		(UnitType,				UniqueName,								GreatWorkType)
VALUES	('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_1',		'GREAT_WORK_JFD_RELIC_1'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_2',		'GREAT_WORK_JFD_RELIC_2'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_3',		'GREAT_WORK_JFD_RELIC_3'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_4',		'GREAT_WORK_JFD_RELIC_4'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_5',		'GREAT_WORK_JFD_RELIC_5'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_6',		'GREAT_WORK_JFD_RELIC_6'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_7',		'GREAT_WORK_JFD_RELIC_7'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_8',		'GREAT_WORK_JFD_RELIC_8'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_9',		'GREAT_WORK_JFD_RELIC_9'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_10',		'GREAT_WORK_JFD_RELIC_10'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_11',		'GREAT_WORK_JFD_RELIC_11'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_12',		'GREAT_WORK_JFD_RELIC_12'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_13',		'GREAT_WORK_JFD_RELIC_13'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_14',		'GREAT_WORK_JFD_RELIC_14'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_15',		'GREAT_WORK_JFD_RELIC_15'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_16',		'GREAT_WORK_JFD_RELIC_16'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_17',		'GREAT_WORK_JFD_RELIC_17'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_18',		'GREAT_WORK_JFD_RELIC_18'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_19',		'GREAT_WORK_JFD_RELIC_19'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_20',		'GREAT_WORK_JFD_RELIC_20'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_21',		'GREAT_WORK_JFD_RELIC_21'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_22',		'GREAT_WORK_JFD_RELIC_22'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_23',		'GREAT_WORK_JFD_RELIC_23'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_24',		'GREAT_WORK_JFD_RELIC_24'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_25',		'GREAT_WORK_JFD_RELIC_25'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_26',		'GREAT_WORK_JFD_RELIC_26'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_27',		'GREAT_WORK_JFD_RELIC_27'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_28',		'GREAT_WORK_JFD_RELIC_28'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_29',		'GREAT_WORK_JFD_RELIC_29'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_30',		'GREAT_WORK_JFD_RELIC_30'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_31',		'GREAT_WORK_JFD_RELIC_31'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_32',		'GREAT_WORK_JFD_RELIC_32'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_33',		'GREAT_WORK_JFD_RELIC_33'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_34',		'GREAT_WORK_JFD_RELIC_34'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_35',		'GREAT_WORK_JFD_RELIC_35'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_36',		'GREAT_WORK_JFD_RELIC_36'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_37',		'GREAT_WORK_JFD_RELIC_37'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_38',		'GREAT_WORK_JFD_RELIC_38'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_39',		'GREAT_WORK_JFD_RELIC_39'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_40',		'GREAT_WORK_JFD_RELIC_40'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_41',		'GREAT_WORK_JFD_RELIC_41'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_42',		'GREAT_WORK_JFD_RELIC_42'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_43',		'GREAT_WORK_JFD_RELIC_43'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_44',		'GREAT_WORK_JFD_RELIC_44'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_45',		'GREAT_WORK_JFD_RELIC_45'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_46',		'GREAT_WORK_JFD_RELIC_46'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_47',		'GREAT_WORK_JFD_RELIC_47'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_48',		'GREAT_WORK_JFD_RELIC_48'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_49',		'GREAT_WORK_JFD_RELIC_49'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_50',		'GREAT_WORK_JFD_RELIC_50'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_51',		'GREAT_WORK_JFD_RELIC_51'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_52',		'GREAT_WORK_JFD_RELIC_52'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_53',		'GREAT_WORK_JFD_RELIC_53'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_54',		'GREAT_WORK_JFD_RELIC_54'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_55',		'GREAT_WORK_JFD_RELIC_55'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_56',		'GREAT_WORK_JFD_RELIC_56'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_57',		'GREAT_WORK_JFD_RELIC_57'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_58',		'GREAT_WORK_JFD_RELIC_58'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_59',		'GREAT_WORK_JFD_RELIC_59'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_60',		'GREAT_WORK_JFD_RELIC_60'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_61',		'GREAT_WORK_JFD_RELIC_61'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_62',		'GREAT_WORK_JFD_RELIC_62'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_63',		'GREAT_WORK_JFD_RELIC_63'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_64',		'GREAT_WORK_JFD_RELIC_64'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_65',		'GREAT_WORK_JFD_RELIC_65'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_66',		'GREAT_WORK_JFD_RELIC_66'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_67',		'GREAT_WORK_JFD_RELIC_67'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_68',		'GREAT_WORK_JFD_RELIC_68'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_69',		'GREAT_WORK_JFD_RELIC_69'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_70',		'GREAT_WORK_JFD_RELIC_70'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_71',		'GREAT_WORK_JFD_RELIC_71'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_72',		'GREAT_WORK_JFD_RELIC_72'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_73',		'GREAT_WORK_JFD_RELIC_73'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_74',		'GREAT_WORK_JFD_RELIC_74'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_75',		'GREAT_WORK_JFD_RELIC_75'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_76',		'GREAT_WORK_JFD_RELIC_76'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_77',		'GREAT_WORK_JFD_RELIC_77'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_78',		'GREAT_WORK_JFD_RELIC_78'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_79',		'GREAT_WORK_JFD_RELIC_79'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_80',		'GREAT_WORK_JFD_RELIC_80'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_81',		'GREAT_WORK_JFD_RELIC_81'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_82',		'GREAT_WORK_JFD_RELIC_82'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_83',		'GREAT_WORK_JFD_RELIC_83'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_84',		'GREAT_WORK_JFD_RELIC_84'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_85',		'GREAT_WORK_JFD_RELIC_85'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_86',		'GREAT_WORK_JFD_RELIC_86'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_87',		'GREAT_WORK_JFD_RELIC_87'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_88',		'GREAT_WORK_JFD_RELIC_88'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_89',		'GREAT_WORK_JFD_RELIC_89'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_90',		'GREAT_WORK_JFD_RELIC_90'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_91',		'GREAT_WORK_JFD_RELIC_91'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_92',		'GREAT_WORK_JFD_RELIC_92'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_93',		'GREAT_WORK_JFD_RELIC_93'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_94',		'GREAT_WORK_JFD_RELIC_94'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_95',		'GREAT_WORK_JFD_RELIC_95'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_96',		'GREAT_WORK_JFD_RELIC_96'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_97',		'GREAT_WORK_JFD_RELIC_97'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_98',		'GREAT_WORK_JFD_RELIC_98'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_99',		'GREAT_WORK_JFD_RELIC_99'),
		('UNIT_PROPHET',		'TXT_KEY_UNIT_JFD_PROPHET_NAME_100',	'GREAT_WORK_JFD_RELIC_100');
UPDATE Unit_UniqueNames SET GreatWorkType = NULL WHERE UnitType = 'UNIT_PROPHET';
--DELETE FROM Unit_UniqueNames WHERE UnitType = 'UNIT_PROPHET'
--AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_RTP_PIETY_GREAT_PROPHET_ARTIFACTS' AND Value = 0);
--==========================================================================================================================
--==========================================================================================================================