--==========================================================================================================================	
-- AUDIO
--==========================================================================================================================			
-- Audio_Sounds
--------------------------------------------------------------------------------------------------------------------------	
INSERT OR REPLACE INTO Audio_Sounds
		(SoundID, 									FileName, 						LoadType)
VALUES	('SND_JFD_SECULARIZATION', 					'Secularization', 				'DynamicResident'),
		('SND_VICTORY_JFD_RELIGIOUS', 				'Victory_Religious', 			'DynamicResident'),
		--Buildings
		('SND_BUILDING_JFD_ALTAR', 					'Altar',						'DynamicResident'),
		('SND_BUILDING_JFD_BASILICA', 				'Basilica',						'DynamicResident'),
		('SND_BUILDING_JFD_CHURCH', 				'Church',						'DynamicResident'),
		('SND_BUILDING_JFD_DAOGUAN', 				'Doaguan',						'DynamicResident'),
		('SND_BUILDING_JFD_FIRE_TEMPLE', 			'FireTemple',					'DynamicResident'),
		('SND_BUILDING_JFD_GRAND_INQUISITION', 		'GrandInquisition',				'DynamicResident'),
		('SND_BUILDING_JFD_GURDWARA', 				'Gurdwara',						'DynamicResident'),
		('SND_BUILDING_JFD_HERMETIC_ORDER', 		'HermeticOrder',				'DynamicResident'),
		('SND_BUILDING_JFD_MANDIR', 				'Mandir',						'DynamicResident'),
		('SND_BUILDING_JFD_OOVO', 					'Oovo',							'DynamicResident'),
		('SND_BUILDING_JFD_SPANISH_INQUISITION', 	'SpanishInquisition',			'DynamicResident'),
		('SND_BUILDING_JFD_SYNAGOGUE', 				'Synagogue',					'DynamicResident'),
		('SND_BUILDING_JFD_TEMPLE_LITEARTURE', 		'TempleLiterature',				'DynamicResident'),
		('SND_BUILDING_JFD_TORII', 					'Torii',						'DynamicResident'),
		--Contracts
		('SND_CONTRACT_BUDDHISM_ACTIVATE', 			'BuddistMissActivate', 			'DynamicResident'),
		('SND_CONTRACT_CATHOLICISM_ACTIVATE', 		'ChristMissionaryActivate', 	'DynamicResident'),
		('SND_CONTRACT_CONFUCIANISM_ACTIVATE', 		'ConfucianMissActivate', 		'DynamicResident'),
		('SND_CONTRACT_HINDUISM_ACTIVATE', 			'HinduMissActivate', 			'DynamicResident'),
		('SND_CONTRACT_ISLAM_ACTIVATE', 			'IslamicMissActivate', 			'DynamicResident'),
		('SND_CONTRACT_JUDAISM_ACTIVATE', 			'JewishMissActivate', 			'DynamicResident'),
		('SND_CONTRACT_TAOISM_ACTIVATE', 			'TaoistMissActivate', 			'DynamicResident'),
		('SND_CONTRACT_ZOROASTRIANISM_ACTIVATE', 	'ZoroMissActivate', 			'DynamicResident'),
		--Generic
		('SND_CITY_CONVERTS_RELIGION', 				'ReligionConvert', 				'DynamicResident'),
		('SND_UNIT_GREAT_PROPHET_ACTIVATE', 		'GreatProphetActivate', 		'DynamicResident'),
		('SND_GREAT_WORK_JFD_RELIC', 				'JFD_PatriarchyFX', 			'DynamicResident'),
		--Institutions
		('SND_INSTITUTION_JFD_CALIPHATE', 			'JFD_CaliphateFX', 				'DynamicResident'),
		('SND_INSTITUTION_JFD_PAPACY', 				'JFD_PapacyFX', 				'DynamicResident'),
		('SND_INSTITUTION_JFD_MANDATE', 			'JFD_MandateOfHeavenFX', 		'DynamicResident'),
		--Religions	
		('SND_JFD_AMATONGO', 						'JFD_Amatongo', 				'DynamicResident'),
		('SND_JFD_ANDEAN', 							'JFD_Andean', 					'DynamicResident'),
		('SND_JFD_ANGAKKUQISM', 					'JFD_Angakkuqism', 				'DynamicResident'),
		('SND_JFD_ANGLICANISM', 					'JFD_Anglicanism', 				'DynamicResident'),
		('SND_JFD_ANKATTU', 						'JFD_Ankattu', 					'DynamicResident'),
		('SND_JFD_ASHURISM', 						'JFD_Ashurism', 				'DynamicResident'),
		('SND_JFD_ATANODJUWAJA', 					'JFD_Atanodjuwaja', 			'DynamicResident'),
		('SND_JFD_ATENISM', 						'JFD_Atenism', 					'DynamicResident'),
		('SND_JFD_BAHAI', 							'JFD_Bahai', 					'DynamicResident'),
		('SND_JFD_BAPTIST', 						'JFD_Baptist', 					'DynamicResident'),
		('SND_JFD_BOGOMILISM', 						'JFD_Bogomilism', 				'DynamicResident'),
		('SND_JFD_BUDDHISM', 						'JFD_Buddhism', 				'DynamicResident'),
		('SND_JFD_CALVINISM', 						'JFD_Calvinism', 				'DynamicResident'),
		('SND_JFD_CANAANISM', 						'JFD_Canaanism', 				'DynamicResident'),
		('SND_JFD_CATHARISM', 						'JFD_Cathar', 					'DynamicResident'),
		('SND_JFD_CATHOLICISM', 					'JFD_Catholicism', 				'DynamicResident'),
		('SND_JFD_CHALDEANISM', 					'JFD_Chaldeanism', 				'DynamicResident'),
		('SND_JFD_CONFUCIANISM', 					'JFD_Confucianism', 			'DynamicResident'),
		('SND_JFD_CHURCH_OF_THE_EAST', 				'JFD_ChurchOfTheEast', 			'DynamicResident'),
		('SND_JFD_DIONYSIANISM', 					'JFD_Dionysian', 				'DynamicResident'),
		('SND_JFD_DRUIDISM', 						'JFD_Druidism', 				'DynamicResident'),
		('SND_JFD_DRUZE', 							'JFD_Druze', 					'DynamicResident'),
		('SND_JFD_ELEUSINIAN', 						'JFD_Eleusinian', 				'DynamicResident'),
		('SND_JFD_FAT_ROOG', 						'JFD_Fat_Roog', 				'DynamicResident'),
		('SND_JFD_FORN_SIDR', 						'JFD_Forn_Sidr', 				'DynamicResident'),
		('SND_JFD_HELLENISM', 						'JFD_Hellenism', 				'DynamicResident'),
		('SND_JFD_HEROS_KARABAZMOS', 				'JFD_HerosKarabazmos', 			'DynamicResident'),
		('SND_JFD_HINDUISM', 						'JFD_Hinduism', 				'DynamicResident'),
		('SND_JFD_HUSITISM', 						'JFD_Hussite', 					'DynamicResident'),
		('SND_JFD_IBADI', 							'JFD_Ibadi', 					'DynamicResident'),
		('SND_JFD_IMPERIAL_CULT', 					'JFD_ImperialCult', 			'DynamicResident'),
		('SND_JFD_ITAN', 							'JFD_Itan', 					'DynamicResident'),
		('SND_JFD_JAINISM', 						'JFD_Jainism', 					'DynamicResident'),
		('SND_JFD_JUDAISM', 						'JFD_Judaism', 					'DynamicResident'),
		('SND_JFD_KACHINA', 						'JFD_Kachina', 					'DynamicResident'),
		('SND_JFD_LAIBONI', 						'JFD_Laiboni', 					'DynamicResident'),
		('SND_JFD_LIIM_DINGERMES', 					'JFD_LiimDingermes', 			'DynamicResident'),
		('SND_JFD_LUTHERISM', 						'JFD_Lutherism', 				'DynamicResident'),
		('SND_JFD_MAHAYANA', 						'JFD_Mahayana', 				'DynamicResident'),
		('SND_JFD_MANAISM', 						'JFD_Manaism', 					'DynamicResident'),
		('SND_JFD_MANDEANISM', 						'JFD_Mandeanism', 				'DynamicResident'),
		('SND_JFD_MANICHAEISM', 					'JFD_Manichaeism', 				'DynamicResident'),
		('SND_JFD_MESOPOTAMIC', 					'JFD_Mesopotamic', 				'DynamicResident'),
		('SND_JFD_METHODISM', 						'JFD_Methodism', 				'DynamicResident'),
		('SND_JFD_MIDEWIWIN', 						'JFD_Midewiwin', 				'DynamicResident'),
		('SND_JFD_MORMONISM', 						'JFD_Mormonism', 				'DynamicResident'),
		('SND_JFD_MUISM', 							'JFD_Muism', 					'DynamicResident'),
		('SND_JFD_MUISM', 							'JFD_Muism', 					'DynamicResident'),
		('SND_JFD_NATIVE_AMERICAN', 				'JFD_NativeAmerican', 			'DynamicResident'),
		('SND_JFD_NEOPLATONISM', 					'JFD_Neoplatonism', 			'DynamicResident'),
		('SND_JFD_NOAIDEVUOHTA', 					'JFD_Noaidevuohta', 			'DynamicResident'),
		('SND_JFD_NUM', 							'JFD_Num', 						'DynamicResident'),
		('SND_JFD_NUMENISM', 						'JFD_Numenism', 				'DynamicResident'),
		('SND_JFD_NZAMBIISM', 						'JFD_Nzambiism', 				'DynamicResident'),
		('SND_JFD_ORENDA', 							'JFD_Orenda', 					'DynamicResident'),
		('SND_JFD_ORTHODOXY', 						'JFD_Orthodoxy', 				'DynamicResident'),
		('SND_JFD_ORIENTAL_ORTHODOXY', 				'JFD_OrientalOrthodoxy', 		'DynamicResident'),
		('SND_JFD_PACHISM', 						'JFD_Pachism', 					'DynamicResident'),
		('SND_JFD_PAJELANCA', 						'JFD_Pajelanca', 				'DynamicResident'),
		('SND_JFD_PESEDJET', 						'JFD_Pesedjet', 				'DynamicResident'),
		('SND_JFD_ROMUVA', 							'JFD_Romuva', 					'DynamicResident'),
		('SND_JFD_SAMAN', 							'JFD_Saman', 					'DynamicResident'),
		('SND_JFD_SATSANA_PHI', 					'JFD_SatsanaPhi', 				'DynamicResident'),
		('SND_JFD_SHAKTISM', 						'JFD_Shaktism', 				'DynamicResident'),
		('SND_JFD_SHAIVISM', 						'JFD_Shaivism', 				'DynamicResident'),
		('SND_JFD_SHIA', 							'JFD_Shia', 					'DynamicResident'),
		('SND_JFD_SHINTO', 							'JFD_Shinto', 					'DynamicResident'),
		('SND_JFD_SIKHISM', 						'JFD_Sikhism', 					'DynamicResident'),
		('SND_JFD_SLAVIANISM', 						'JFD_Slavanism', 				'DynamicResident'),
		('SND_JFD_SUNNI', 							'JFD_Sunni', 					'DynamicResident'),
		('SND_JFD_TAOISM', 							'JFD_Taoism', 					'DynamicResident'),
		('SND_JFD_TENGRIISM', 						'JFD_Tengriism', 				'DynamicResident'),
		('SND_JFD_TJUKURPA', 						'JFD_Tjukurpa', 				'DynamicResident'),
		('SND_JFD_TLATEOMATILIZTLI', 				'JFD_Tlatoematiliztli', 		'DynamicResident'),
		('SND_JFD_TZOLKIN', 						'JFD_Tzolkin', 					'DynamicResident'),
		('SND_JFD_VAISHNAVISM', 					'JFD_Vaishnavism', 				'DynamicResident'),
		('SND_JFD_VAJRAYANA', 						'JFD_Vajrayana', 				'DynamicResident'),
		('SND_JFD_VEDISM', 							'JFD_Vedism', 					'DynamicResident'),
		('SND_JFD_VOODOO', 							'JFD_Voodoo', 					'DynamicResident'),
		('SND_JFD_WAKAN_TANKA', 					'JFD_WakanTanka', 				'DynamicResident'),
		('SND_JFD_WILRAN_MAPU', 					'JFD_WilranMapu', 				'DynamicResident'),
		('SND_JFD_YAZDANISM', 						'JFD_Yazdanism', 				'DynamicResident'),
		('SND_JFD_ZEMIISM', 						'JFD_Zemiism', 					'DynamicResident'),
		('SND_JFD_ZOROASTRIANISM', 					'JFD_Zoroastrianism', 			'DynamicResident'),
		--Wonders
		('SND_WONDER_SPEECH_JFD_ABU_SIMBEL', 		'Wonder_AbuSimbel',				'DynamicResident'),
		('SND_WONDER_SPEECH_JFD_BUDDHAS_BAMIYAN', 	'Wonder_BuddhaBamiyan',			'DynamicResident'),
		('SND_WONDER_SPEECH_JFD_COLOGNE', 			'Wonder_Cologne',				'DynamicResident'),
		('SND_WONDER_SPEECH_JFD_DOME_ROCK', 		'Wonder_DomeRock',				'DynamicResident'),
		('SND_WONDER_SPEECH_JFD_PANTHEON', 			'Wonder_Pantheon',				'DynamicResident'),
		('SND_WONDER_SPEECH_JFD_SOLOMON_TEMPLE', 	'Wonder_Solomon',				'DynamicResident'),
		('SND_WONDER_SPEECH_JFD_TODAI', 			'Wonder_Todai',					'DynamicResident'),
		('SND_WONDER_SPEECH_JFD_TEMPLE_HEAVEN', 	'Wonder_TempleHeaven',			'DynamicResident');
--------------------------------------------------------------------------------------------------------------------------
-- Audio_2DSounds
--------------------------------------------------------------------------------------------------------------------------	
INSERT OR REPLACE INTO Audio_2DSounds
		(ScriptID, 									SoundID, 									DontTriggerDuplicates,	TaperSoundtrackVolume,	MinVolume,	MaxVolume,	SoundType)
VALUES	('AS2D_JFD_SECULARIZATION', 				'SND_JFD_SECULARIZATION', 					1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_VICTORY_JFD_RELIGIOUS', 				'SND_VICTORY_JFD_RELIGIOUS', 				1,						0.75,					100,		100,		'GAME_SFX'),
		--Buildings
		('AS2D_BUILDING_JFD_ALTAR', 				'SND_BUILDING_JFD_ALTAR', 					1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_BUILDING_JFD_BASILICA', 				'SND_BUILDING_JFD_BASILICA', 				1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_BUILDING_JFD_CHURCH', 				'SND_BUILDING_JFD_CHURCH', 					1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_BUILDING_JFD_DAOGUAN', 				'SND_BUILDING_JFD_DAOGUAN', 				1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_BUILDING_JFD_FIRE_TEMPLE', 			'SND_BUILDING_JFD_FIRE_TEMPLE', 			1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_BUILDING_JFD_GRAND_INQUISITION',		'SND_BUILDING_JFD_GRAND_INQUISITION',		1,						0.0	,					75,			75,			'GAME_SFX'),
		('AS2D_BUILDING_JFD_GURDWARA', 				'SND_BUILDING_JFD_GURDWARA', 				1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_BUILDING_JFD_HERMETIC_ORDER', 		'SND_BUILDING_JFD_HERMETIC_ORDER', 			1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_BUILDING_JFD_MANDIR', 				'SND_BUILDING_JFD_MANDIR', 					1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_BUILDING_JFD_OOVO', 					'SND_BUILDING_JFD_OOVO', 					1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_BUILDING_JFD_SPANISH_INQUISITION',	'SND_BUILDING_JFD_SPANISH_INQUISITION',		1,						0.0	,					75,			75,			'GAME_SFX'),
		('AS2D_BUILDING_JFD_SYNAGOGUE', 			'SND_BUILDING_JFD_SYNAGOGUE', 				1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_BUILDING_JFD_TEMPLE_LITERATURE', 	'SND_BUILDING_JFD_TEMPLE_LITERATURE', 		1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_BUILDING_JFD_TORII', 				'SND_BUILDING_JFD_TORII', 					1,						0.0,					75,			75,			'GAME_SFX'),
		--Contracts
		('AS2D_CONTRACT_BUDDHISM_ACTIVATE', 		'SND_CONTRACT_BUDDHISM_ACTIVATE', 			1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_CONTRACT_CATHOLICISM_ACTIVATE', 		'SND_CONTRACT_CATHOLICISM_ACTIVATE', 		1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_CONTRACT_CONFUCIANISM_ACTIVATE', 	'SND_CONTRACT_CONFUCIANISM_ACTIVATE', 		1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_CONTRACT_HINDUISM_ACTIVATE', 		'SND_CONTRACT_HINDUISM_ACTIVATE', 			1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_CONTRACT_ISLAM_ACTIVATE', 			'SND_CONTRACT_ISLAM_ACTIVATE', 				1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_CONTRACT_JUDAISM_ACTIVATE', 			'SND_CONTRACT_JUDAISM_ACTIVATE', 			1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_CONTRACT_TAOISM_ACTIVATE', 			'SND_CONTRACT_TAOISM_ACTIVATE', 			1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_CONTRACT_ZOROASTRIANISM_ACTIVATE', 	'SND_CONTRACT_ZOROASTRIANISM_ACTIVATE', 	1,						0.0,					75,			75,			'GAME_SFX'),
		--Generic                                   -Generic
		('AS2D_CITY_CONVERTS_RELIGION', 			'SND_CITY_CONVERTS_RELIGION', 				1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_GREAT_WORK_JFD_RELIC', 				'SND_GREAT_WORK_JFD_RELIC', 				1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_UNIT_GREAT_PROPHET_ACTIVATE', 		'SND_UNIT_GREAT_PROPHET_ACTIVATE', 			1,						0.0,					75,			75,			'GAME_SFX'),
		--Institutions                              -Institutions
		('AS2D_INSTITUTION_JFD_CALIPHATE', 			'SND_INSTITUTION_JFD_CALIPHATE', 			1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_INSTITUTION_JFD_PAPACY', 			'SND_INSTITUTION_JFD_PAPACY', 				1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_INSTITUTION_JFD_MANDATE', 			'SND_INSTITUTION_JFD_MANDATE', 				1,						0.0,					75,			75,			'GAME_SFX'),
		--Religions	                                -Religions	
		('AS2D_JFD_AMATONGO', 						'SND_JFD_AMATONGO', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_ANDEAN', 						'SND_JFD_ANDEAN', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_ANGAKKUQISM', 					'SND_JFD_ANGAKKUQISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_ANGLICANISM', 					'SND_JFD_ANGLICANISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_ANKATTU', 						'SND_JFD_ANKATTU', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_ASHURISM', 						'SND_JFD_ASHURISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_ATANODJUWAJA', 					'SND_JFD_ATANODJUWAJA', 					1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_ATENISM', 						'SND_JFD_ATENISM', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_BAHAI', 							'SND_JFD_BAHAI', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_BAPTIST', 						'SND_JFD_BAPTIST', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_BOGOMILISM', 					'SND_JFD_BOGOMILISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_BUDDHISM', 						'SND_JFD_BUDDHISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_CALVINISM', 						'SND_JFD_CALVINISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_CANAANISM', 						'SND_JFD_CANAANISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_CATHARISM', 						'SND_JFD_CATHARISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_CATHOLICISM', 					'SND_JFD_CATHOLICISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_CHALDEANISM', 					'SND_JFD_CHALDEANISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_CONFUCIANISM', 					'SND_JFD_CONFUCIANISM', 					1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_CHURCH_OF_THE_EAST', 			'SND_JFD_CHURCH_OF_THE_EAST', 				1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_DIONYSIANISM', 					'SND_JFD_DIONYSIANISM', 					1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_DRUIDISM', 						'SND_JFD_DRUIDISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_DRUZE', 							'SND_JFD_DRUZE', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_FAT_ROOG', 						'SND_JFD_FAT_ROOG', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_FORN_SIDR', 						'SND_JFD_FORN_SIDR', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_HELLENISM', 						'SND_JFD_HELLENISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_HEROS_KARABAZMOS', 				'SND_JFD_HEROS_KARABAZMOS', 				1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_HINDUISM', 						'SND_JFD_HINDUISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_HUSITISM', 						'SND_JFD_HUSITISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_IBADI', 							'SND_JFD_IBADI', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_IMPERIAL_CULT', 					'SND_JFD_IMPERIAL_CULT', 					1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_ITAN', 							'SND_JFD_ITAN', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_JAINISM', 						'SND_JFD_JAINISM', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_JUDAISM', 						'SND_JFD_JUDAISM', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_KACHINA', 						'SND_JFD_KACHINA', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_LAIBONI', 						'SND_JFD_LAIBONI', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_LIIM_DINGERMES', 				'SND_JFD_LIIM_DINGERMES', 					1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_LUTHERISM', 						'SND_JFD_LUTHERISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_MAHAYANA', 						'SND_JFD_MAHAYANA', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_MANAISM', 						'SND_JFD_MANAISM', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_MANDEANISM', 					'SND_JFD_MANDEANISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_MANICHAEISM', 					'SND_JFD_MANICHAEISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_MESOPOTAMIC', 					'SND_JFD_MESOPOTAMIC', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_METHODISM', 						'SND_JFD_METHODISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_MIDEWIWIN', 						'SND_JFD_MIDEWIWIN', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_MORMONISM', 						'SND_JFD_MORMONISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_MUISM', 							'SND_JFD_MUISM', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_NATIVE_AMERICAN', 				'SND_JFD_NATIVE_AMERICAN', 					1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_NEOPLATONISM', 					'SND_JFD_NEOPLATONISM', 					1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_NOAIDEVUOHTA', 					'SND_JFD_NOAIDEVUOHTA', 					1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_NUM', 							'SND_JFD_NUM', 								1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_NUMENISM', 						'SND_JFD_NUMENISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_NZAMBIISM', 						'SND_JFD_NZAMBIISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_ORENDA', 						'SND_JFD_ORENDA', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_ORTHODOXY', 						'SND_JFD_ORTHODOXY', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_ORIENTAL_ORTHODOXY', 			'SND_JFD_ORIENTAL_ORTHODOXY', 				1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_PACHISM', 						'SND_JFD_PACHISM', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_PAJELANCA', 						'SND_JFD_PAJELANCA', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_PESEDJET', 						'SND_JFD_PESEDJET', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_ROMUVA', 						'SND_JFD_ROMUVA', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_SAMAN', 							'SND_JFD_SAMAN', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_SATANISM', 						'SND_JFD_SATANISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_SATSANA_PHI', 					'SND_JFD_SATSANA_PHI', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_SHAKTISM', 						'SND_JFD_SHAKTISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_SHAIVISM', 						'SND_JFD_SHAIVISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_SHIA', 							'SND_JFD_SHIA', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_SHINTO', 						'SND_JFD_SHINTO', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_SIKHISM', 						'SND_JFD_SIKHISM', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_SLAVIANISM', 					'SND_JFD_SLAVIANISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_SUNNI', 							'SND_JFD_SUNNI', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_TAOISM', 						'SND_JFD_TAOISM', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_TENGRIISM', 						'SND_JFD_TENGRIISM', 						1,						0.0,					60,			60,			'GAME_SFX'),
		('AS2D_JFD_TJUKURPA', 						'SND_JFD_TJUKURPA', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_TLATEOMATILIZTLI', 				'SND_JFD_TLATEOMATILIZTLI', 				1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_TZOLKIN', 						'SND_JFD_TZOLKIN', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_WAKAN_TANKA', 					'SND_JFD_WAKAN_TANKA', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_WILRAN_MAPU', 					'SND_JFD_WILRAN_MAPU', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_VAISHNAVISM', 					'SND_JFD_VAISHNAVISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_VAJRAYANA', 						'SND_JFD_VAJRAYANA', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_VEDISM', 						'SND_JFD_VEDISM', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_VOODOO', 						'SND_JFD_VOODOO', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_YAZDANISM', 						'SND_JFD_YAZDANISM', 						1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_ZEMIISM', 						'SND_JFD_ZEMIISM', 							1,						0.0,					75,			75,			'GAME_SFX'),
		('AS2D_JFD_ZOROASTRIANISM', 				'SND_JFD_ZOROASTRIANISM', 					1,						0.0,					75,			75,			'GAME_SFX'),
		--Wonders
		('AS2D_WONDER_SPEECH_JFD_ABU_SIMBEL', 		'SND_WONDER_SPEECH_JFD_ABU_SIMBEL', 		1,						0.0,					75,			75,			'GAME_MUSIC_STINGS'),
		('AS2D_WONDER_SPEECH_JFD_BUDDHAS_BAMIYAN', 	'SND_WONDER_SPEECH_JFD_BUDDHAS_BAMIYAN', 	1,						0.0,					75,			75,			'GAME_MUSIC_STINGS'),
		('AS2D_WONDER_SPEECH_JFD_COLOGNE', 			'SND_WONDER_SPEECH_JFD_COLOGNE', 			1,						0.0,					75,			75,			'GAME_MUSIC_STINGS'),
		('AS2D_WONDER_SPEECH_JFD_DOME_ROCK', 		'SND_WONDER_SPEECH_JFD_DOME_ROCK', 			1,						0.0,					75,			75,			'GAME_MUSIC_STINGS'),
		('AS2D_WONDER_SPEECH_JFD_PANTHEON', 		'SND_WONDER_SPEECH_JFD_PANTHEON', 			1,						0.0,					75,			75,			'GAME_MUSIC_STINGS'),
		('AS2D_WONDER_SPEECH_JFD_SOLOMON_TEMPLE', 	'SND_WONDER_SPEECH_JFD_SOLOMON_TEMPLE', 	1,						0.0,					75,			75,			'GAME_MUSIC_STINGS'),
		('AS2D_WONDER_SPEECH_JFD_TODAI', 			'SND_WONDER_SPEECH_JFD_TODAI', 				1,						0.0,					75,			75,			'GAME_MUSIC_STINGS'),
		('AS2D_WONDER_SPEECH_JFD_TEMPLE_HEAVEN', 	'SND_WONDER_SPEECH_JFD_TEMPLE_HEAVEN', 		1,						0.0,					75,			75,			'GAME_MUSIC_STINGS');
--==========================================================================================================================
--==========================================================================================================================