--==========================================================================================================================
-- AUDIO
--==========================================================================================================================	
-- Audio_Sounds
------------------------------	
INSERT INTO Audio_Sounds 
		(SoundID, 									Filename, 								LoadType)
VALUES	('SND_BUILDING_JFD_GENERIC', 				'Generic',								'DynamicResident'),
		('SND_BUILDING_JFD_AMPHITHEATER', 			'Amphitheater',							'DynamicResident'),
		('SND_BUILDING_JFD_APOTHECARY', 			'Apothecary',							'DynamicResident'),
		('SND_BUILDING_JFD_AQUEDUCT', 				'Aqueduct',								'DynamicResident'),
		('SND_BUILDING_JFD_ARSENAL', 				'Arsenal',								'DynamicResident'),
		('SND_BUILDING_JFD_ARTISTS_GUILD', 			'ArtistsGuild',							'DynamicResident'),
		('SND_BUILDING_JFD_BANK', 					'Bank',									'DynamicResident'),
		('SND_BUILDING_JFD_BARRACKS', 				'Barracks',								'DynamicResident'),
		('SND_BUILDING_JFD_BASTION', 				'Bastion',								'DynamicResident'),
		('SND_BUILDING_JFD_BAZAAR', 				'Bazaar',								'DynamicResident'),
		('SND_BUILDING_JFD_BLAST_FURNACE', 			'BlastFurnace',							'DynamicResident'),
		('SND_BUILDING_JFD_BOMB_SHELTER', 			'Bunker',								'DynamicResident'),
		('SND_BUILDING_JFD_BROADCAST_TOWER', 		'BroadcastTower',						'DynamicResident'),
		('SND_BUILDING_JFD_BURIAL_TOMB', 			'BurialTomb',							'DynamicResident'),
		('SND_BUILDING_JFD_CANDI', 					'Candi',								'DynamicResident'),
		('SND_BUILDING_JFD_CARAVANSARY', 			'Caravansary',							'DynamicResident'),
		('SND_BUILDING_JFD_CATHEDRAL', 				'Cathedral',							'DynamicResident'),
		('SND_BUILDING_JFD_CASTLE', 				'Castle',								'DynamicResident'),
		('SND_BUILDING_JFD_CEILIDH_HALL', 			'CeilidhHall',							'DynamicResident'),
		('SND_BUILDING_JFD_CINEMA', 				'Cinema',								'DynamicResident'),
		('SND_BUILDING_JFD_CIRCUS', 				'Circus',								'DynamicResident'),
		('SND_BUILDING_JFD_CIRCUS_MAXIMUS', 		'CircusMaximus',						'DynamicResident'),
		('SND_BUILDING_JFD_CISTERN', 				'Cistern',								'DynamicResident'),
		('SND_BUILDING_JFD_CLOTH_MILL', 			'ClothMill',							'DynamicResident'),
		('SND_BUILDING_JFD_COAL_PLANT', 			'CoalStation',							'DynamicResident'),
		('SND_BUILDING_JFD_COFFEE_HOUSE', 			'CoffeeHouse',							'DynamicResident'),
		('SND_BUILDING_JFD_COLOSSEUM', 				'Colosseum',							'DynamicResident'),
		('SND_BUILDING_JFD_CONSTABULARY', 			'Constabulary',							'DynamicResident'),
		('SND_BUILDING_JFD_COURTHOUSE', 			'Courthouse',							'DynamicResident'),
		('SND_BUILDING_JFD_DRILL_ACADEMY', 			'DrillAcademy',							'DynamicResident'),
		('SND_BUILDING_JFD_DRYDOCK', 				'Drydock',								'DynamicResident'),
		('SND_BUILDING_JFD_DUCAL_STABLE', 			'DucalStable',							'DynamicResident'),
		('SND_BUILDING_JFD_EAST_INDIA_COMPANY',		'EastIndiaCompany',						'DynamicResident'),
		('SND_BUILDING_JFD_FACTORY', 				'Factory',								'DynamicResident'),
		('SND_BUILDING_JFD_FLOATING_GARDENS', 		'FloatingGardens',						'DynamicResident'),
		('SND_BUILDING_JFD_FORGE', 					'Forge',								'DynamicResident'),
		('SND_BUILDING_JFD_GALLERY', 				'Gallery',								'DynamicResident'),
		('SND_BUILDING_JFD_GARDEN', 				'Garden',								'DynamicResident'),
		('SND_BUILDING_JFD_GRAIN_ELEVATOR', 		'GrainElevator',						'DynamicResident'),
		('SND_BUILDING_JFD_GRANARY', 				'Granary',								'DynamicResident'),
		('SND_BUILDING_JFD_GRAND_TEMPLE', 			'GrandTemple',							'DynamicResident'),
		('SND_BUILDING_JFD_GROCER', 				'Grocer',								'DynamicResident'),
		('SND_BUILDING_JFD_GUNSMITH', 				'Gunsmith',								'DynamicResident'),
		('SND_BUILDING_JFD_HANSE', 					'Hanse',								'DynamicResident'),
		('SND_BUILDING_JFD_HARBOR', 				'Harbor',								'DynamicResident'),
		('SND_BUILDING_JFD_HERBALIST', 				'Herbalist',							'DynamicResident'),
		('SND_BUILDING_JFD_HEROIC_EPIC', 			'HeroicEpic',							'DynamicResident'),
		('SND_BUILDING_JFD_HORSE_MILL', 			'HorseMill',							'DynamicResident'),
		('SND_BUILDING_JFD_HOSPITAL', 				'Hospital',								'DynamicResident'),
		('SND_BUILDING_JFD_HOTEL', 					'Hotel',								'DynamicResident'),
		('SND_BUILDING_JFD_HYDRO_PLANT', 			'HydroPlant',							'DynamicResident'),
		('SND_BUILDING_JFD_IKANDA', 				'Ikanda',								'DynamicResident'),
		('SND_BUILDING_JFD_INTELLIGENCE_AGENCY',	'IntelligenceAgency',					'DynamicResident'),
		('SND_BUILDING_JFD_IRONWORKS',				'Ironworks',							'DynamicResident'),
		('SND_BUILDING_JFD_JAIL', 					'Jail',									'DynamicResident'),
		('SND_BUILDING_JFD_KREPOST', 				'Krepost',								'DynamicResident'),
		('SND_BUILDING_JFD_LABORATORY', 			'Laboratory',							'DynamicResident'),
		('SND_BUILDING_JFD_LIBRARY', 				'Library',								'DynamicResident'),
		('SND_BUILDING_JFD_LIGHTHOUSE', 			'Lighthouse',							'DynamicResident'),
		('SND_BUILDING_JFD_LONGHOUSE', 				'Longhouse',							'DynamicResident'),
		('SND_BUILDING_JFD_MANOR', 					'Manor',								'DynamicResident'),
		('SND_BUILDING_JFD_MANSION', 				'Mansion',								'DynamicResident'),
		('SND_BUILDING_JFD_MARKET', 				'Market',								'DynamicResident'),
		('SND_BUILDING_JFD_MEDICAL_LAB', 			'MedicalLab',							'DynamicResident'),
		('SND_BUILDING_JFD_MENAGERIE', 				'Menagerie',							'DynamicResident'),
		('SND_BUILDING_JFD_MILITARY_ACADEMY', 		'MilitaryAcademy',						'DynamicResident'),
		('SND_BUILDING_JFD_MILITARY_BASE', 			'MilitaryBase',							'DynamicResident'),
		('SND_BUILDING_JFD_MINT', 					'Mint',									'DynamicResident'),
		('SND_BUILDING_JFD_MONASTERY', 				'Monastery',							'DynamicResident'),
		('SND_BUILDING_JFD_MONUMENT', 				'Monument',								'DynamicResident'),
		('SND_BUILDING_JFD_MOSQUE', 				'Mosque',								'DynamicResident'),
		('SND_BUILDING_JFD_MUD_PYRAMID_MOSQUE', 	'MudMosque',							'DynamicResident'),
		('SND_BUILDING_JFD_MUGHAL_FORT', 			'MughalFort',							'DynamicResident'),
		('SND_BUILDING_JFD_MUSEUM', 				'Museum',								'DynamicResident'),
		('SND_BUILDING_JFD_MUSICIANS_GUILD', 		'MusiciansGuild',						'DynamicResident'),
		('SND_BUILDING_JFD_NATIONAL_COLLEGE', 		'NationalCollege',						'DynamicResident'),
		('SND_BUILDING_JFD_NATIONAL_EPIC', 			'NationalEpic',							'DynamicResident'),
		('SND_BUILDING_JFD_NATIONAL_TREASURY', 		'NationalTreasury',						'DynamicResident'),
		('SND_BUILDING_JFD_OBSERVATORY', 			'Observatory',							'DynamicResident'),
		('SND_BUILDING_JFD_OIL_REFINERY', 			'OilRefinery',							'DynamicResident'),
		('SND_BUILDING_JFD_OPERA_HOUSE', 			'OperaHouse',							'DynamicResident'),
		('SND_BUILDING_JFD_PAGODA', 				'Pagoda',								'DynamicResident'),
		('SND_BUILDING_JFD_PAPER_MAKER', 			'PaperMaker',							'DynamicResident'),
		('SND_BUILDING_JFD_POLICE_STATION', 		'PoliceStation',						'DynamicResident'),
		('SND_BUILDING_JFD_PRISON', 				'Prison',								'DynamicResident'),
		('SND_BUILDING_JFD_PUBLIC_SCHOOL', 			'School',								'DynamicResident'),
		('SND_BUILDING_JFD_PYRAMID', 				'Pyramid',								'DynamicResident'),
		('SND_BUILDING_JFD_RECYCLING_CENTER', 		'RecyclingCenter',						'DynamicResident'),
		('SND_BUILDING_JFD_RED_CROSS', 				'RedCross',								'DynamicResident'),
		('SND_BUILDING_JFD_ROYAL_LIBRARY', 			'RoyalLibrary',							'DynamicResident'),
		('SND_BUILDING_JFD_SALON', 					'Salon',								'DynamicResident'),
		('SND_BUILDING_JFD_SATRAP_COURT', 			'SatrapCourt',							'DynamicResident'),
		('SND_BUILDING_JFD_SEAPORT', 				'Seaport',								'DynamicResident'),
		('SND_BUILDING_JFD_SHRINE', 				'Shrine',								'DynamicResident'),
		('SND_BUILDING_JFD_SOLAR_PLANT', 			'SolarPlant',							'DynamicResident'),
		('SND_BUILDING_JFD_SPACESHIP', 				'SpaceshipFactory',						'DynamicResident'),
		('SND_BUILDING_JFD_STABLE', 				'Stable',								'DynamicResident'),
		('SND_BUILDING_JFD_STADIUM', 				'Stadium',								'DynamicResident'),
		('SND_BUILDING_JFD_STELE', 					'Stele',								'DynamicResident'),
		('SND_BUILDING_JFD_STONEWORKS', 			'Stoneworks',							'DynamicResident'),
		('SND_BUILDING_JFD_STOCK_EXCHANGE', 		'StockMarket',							'DynamicResident'),
		('SND_BUILDING_JFD_SUPERMARKET', 			'Supermarket',							'DynamicResident'),
		('SND_BUILDING_JFD_TAVERN', 				'Tavern',								'DynamicResident'),
		('SND_BUILDING_JFD_TEMPLE', 				'Temple',								'DynamicResident'),
		('SND_BUILDING_JFD_THEATRE', 				'Theatre',								'DynamicResident'),
		('SND_BUILDING_JFD_UNIVERSITY', 			'University',							'DynamicResident'),
		('SND_BUILDING_JFD_VISITORS_CENTER', 		'NationalVisitorsCenter',				'DynamicResident'),
		('SND_BUILDING_JFD_WALLS', 					'Walls',								'DynamicResident'),
		('SND_BUILDING_JFD_WALLS_BABYLON', 			'BabylonWalls',							'DynamicResident'),
		('SND_BUILDING_JFD_WATERMILL', 				'Watermill',							'DynamicResident'),
		('SND_BUILDING_JFD_WIND_FARM', 				'WindFarm',								'DynamicResident'),
		('SND_BUILDING_JFD_WINDMILL', 				'Windmill',								'DynamicResident'),
		('SND_BUILDING_JFD_WAT', 					'Wat',									'DynamicResident'),
		('SND_BUILDING_JFD_WEIGH_HOUSE', 			'WeighHouse',							'DynamicResident'),
		('SND_BUILDING_JFD_WELL', 					'Well',									'DynamicResident'),
		('SND_BUILDING_JFD_WRITERS_GUILD', 			'WritersGuild',							'DynamicResident'),
		('SND_BUILDING_JFD_WORKSHOP', 				'Workshop',								'DynamicResident'),
		('SND_BUILDING_JFD_ZOO', 					'Zoo',									'DynamicResident'),
		('SND_UNIT_JFD_BUILD', 						'UnitBuild',							'DynamicResident'),
		('SND_UNIT_JFD_BUILD_FIN', 					'UnitBuildFin',							'DynamicResident'),
		('SND_UNIT_JFD_PROMOTED', 					'LevelUp',								'DynamicResident');	
------------------------------
-- Audio_2DSounds
------------------------------	
INSERT INTO Audio_2DSounds 
		(ScriptID, 									SoundID, 								SoundType, 				DontTriggerDuplicates,	DontPlayMoreThan,	TaperSoundtrackVolume,	MinVolume, 	MaxVolume)
VALUES	('AS2D_BUILDING_JFD_GENERIC',				'SND_BUILDING_JFD_GENERIC',				'GAME_SFX', 			1,						1,					-1.0,					75, 		75),
		('AS2D_BUILDING_JFD_AMPHITHEATER',			'SND_BUILDING_JFD_AMPHITHEATER',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_APOTHECARY',			'SND_BUILDING_JFD_APOTHECARY',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_AQUEDUCT',				'SND_BUILDING_JFD_AQUEDUCT',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_ARSENAL',				'SND_BUILDING_JFD_ARSENAL',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_ARTISTS_GUILD',			'SND_BUILDING_JFD_ARTISTS_GUILD',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_BANK',					'SND_BUILDING_JFD_BANK',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_BARRACKS',				'SND_BUILDING_JFD_BARRACKS',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_BASTION',				'SND_BUILDING_JFD_BASTION',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_BAZAAR',				'SND_BUILDING_JFD_BAZAAR',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_BLAST_FURNACE',			'SND_BUILDING_JFD_BLAST_FURNACE',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_BOMB_SHELTER',			'SND_BUILDING_JFD_BOMB_SHELTER',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_BROADCAST_TOWER',		'SND_BUILDING_JFD_BROADCAST_TOWER',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_BURIAL_TOMB',			'SND_BUILDING_JFD_BURIAL_TOMB',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_CANDI',					'SND_BUILDING_JFD_CANDI',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_CASTLE',				'SND_BUILDING_JFD_CASTLE',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_CATHEDRAL',				'SND_BUILDING_JFD_CATHEDRAL',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_CARAVANSARY',			'SND_BUILDING_JFD_CARAVANSARY',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_CEILIDH_HALL',			'SND_BUILDING_JFD_CEILIDH_HALL',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_CINEMA',				'SND_BUILDING_JFD_CINEMA',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_CIRCUS',				'SND_BUILDING_JFD_CIRCUS',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_CIRCUS_MAXIMUS',		'SND_BUILDING_JFD_CIRCUS_MAXIMUS',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_CISTERN',				'SND_BUILDING_JFD_CISTERN',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_CLOTH_MILL',			'SND_BUILDING_JFD_CLOTH_MILL',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_COAL_PLANT',			'SND_BUILDING_JFD_COAL_PLANT',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_COFFEE_HOUSE',			'SND_BUILDING_JFD_COFFEE_HOUSE',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_COLOSSEUM',				'SND_BUILDING_JFD_COLOSSEUM',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_CONSTABULARY',			'SND_BUILDING_JFD_CONSTABULARY',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_COURTHOUSE',			'SND_BUILDING_JFD_COURTHOUSE',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_DRILL_ACADEMY',			'SND_BUILDING_JFD_DRILL_ACADEMY',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_DRYDOCK',				'SND_BUILDING_JFD_DRYDOCK',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_DUCAL_STABLE',			'SND_BUILDING_JFD_DUCAL_STABLE',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_EAST_INDIA_COMPANY',	'SND_BUILDING_JFD_EAST_INDIA_COMPANY',	'GAME_SFX', 			1,						1,					-1.0,					75, 		75),
		('AS2D_BUILDING_JFD_FACTORY',				'SND_BUILDING_JFD_FACTORY',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_FLOATING_GARDENS',		'SND_BUILDING_JFD_FLOATING_GARDENS',	'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_FORGE',					'SND_BUILDING_JFD_FORGE',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_GALLERY',				'SND_BUILDING_JFD_GALLERY',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_GARDEN',				'SND_BUILDING_JFD_GARDEN',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_GRAIN_ELEVATOR',		'SND_BUILDING_JFD_GRAIN_ELEVATOR',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_GRANARY',				'SND_BUILDING_JFD_GRANARY',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_GRAND_TEMPLE',			'SND_BUILDING_JFD_GRAND_TEMPLE',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_GROCER',				'SND_BUILDING_JFD_GROCER',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_GUNSMITH',				'SND_BUILDING_JFD_GUNSMITH',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_HANSE',					'SND_BUILDING_JFD_HANSE',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_HARBOR',				'SND_BUILDING_JFD_HARBOR',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_HERBALIST',				'SND_BUILDING_JFD_HERBALIST',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_HEROIC_EPIC',			'SND_BUILDING_JFD_HEROIC_EPIC',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_HORSE_MILL',			'SND_BUILDING_JFD_HORSE_MILL',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_HOSPITAL',				'SND_BUILDING_JFD_HOSPITAL',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_HOTEL',					'SND_BUILDING_JFD_HOTEL',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_HYDRO_PLANT',			'SND_BUILDING_JFD_HYDRO_PLANT',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_IKANDA',				'SND_BUILDING_JFD_IKANDA',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_INTELLIGENCE_AGENCY',	'SND_BUILDING_JFD_INTELLIGENCE_AGENCY',	'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_IRONWORKS',				'SND_BUILDING_JFD_IRONWORKS',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_JAIL',					'SND_BUILDING_JFD_JAIL',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_KREPOST',				'SND_BUILDING_JFD_KREPOST',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_LABORATORY',			'SND_BUILDING_JFD_LABORATORY',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_LIBRARY',				'SND_BUILDING_JFD_LIBRARY',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_LIGHTHOUSE',			'SND_BUILDING_JFD_LIGHTHOUSE',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_LONGHOUSE',				'SND_BUILDING_JFD_LONGHOUSE',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_MANOR',					'SND_BUILDING_JFD_MANOR',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_MARKET',				'SND_BUILDING_JFD_MARKET',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_MEDICAL_LAB',			'SND_BUILDING_JFD_MEDICAL_LAB',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_MENAGERIE',				'SND_BUILDING_JFD_MENAGERIE',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_MILITARY_ACADEMY',		'SND_BUILDING_JFD_MILITARY_ACADEMY',	'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_MILITARY_BASE',			'SND_BUILDING_JFD_MILITARY_BASE',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_MINT',					'SND_BUILDING_JFD_MINT',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_MONASTERY',				'SND_BUILDING_JFD_MONASTERY',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_MANSION',				'SND_BUILDING_JFD_MANSION',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_MONUMENT',				'SND_BUILDING_JFD_MONUMENT',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_MOSQUE',				'SND_BUILDING_JFD_MOSQUE',				'GAME_SFX', 			1,						1,					-1.0,					75, 		75),
		('AS2D_BUILDING_JFD_MUD_PYRAMID_MOSQUE',	'SND_BUILDING_JFD_MUD_PYRAMID_MOSQUE',	'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_MUGHAL_FORT',			'SND_BUILDING_JFD_MUGHAL_FORT',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_MUSEUM',				'SND_BUILDING_JFD_MUSEUM',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_MUSICIANS_GUILD',		'SND_BUILDING_JFD_MUSICIANS_GUILD',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_NATIONAL_COLLEGE',		'SND_BUILDING_JFD_NATIONAL_COLLEGE',	'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_NATIONAL_EPIC',			'SND_BUILDING_JFD_NATIONAL_EPIC',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_NATIONAL_TREASURY',		'SND_BUILDING_JFD_NATIONAL_TREASURY',	'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_OBSERVATORY',			'SND_BUILDING_JFD_OBSERVATORY',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_OIL_REFINERY',			'SND_BUILDING_JFD_OIL_REFINERY',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_OPERA_HOUSE',			'SND_BUILDING_JFD_OPERA_HOUSE',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_PAGODA',				'SND_BUILDING_JFD_PAGODA',				'GAME_SFX', 			1,						1,					-1.0,					75, 		75),
		('AS2D_BUILDING_JFD_PAPER_MAKER',			'SND_BUILDING_JFD_PAPER_MAKER',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_POLICE_STATION',		'SND_BUILDING_JFD_POLICE_STATION',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_PRISON',				'SND_BUILDING_JFD_PRISON',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_PYRAMID',				'SND_BUILDING_JFD_PYRAMID',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_PUBLIC_SCHOOL',			'SND_BUILDING_JFD_PUBLIC_SCHOOL',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_RECYCLING_CENTER',		'SND_BUILDING_JFD_RECYCLING_CENTER',	'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_RED_CROSS',				'SND_BUILDING_JFD_RED_CROSS',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_ROYAL_LIBRARY',			'SND_BUILDING_JFD_ROYAL_LIBRARY',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_SALON',					'SND_BUILDING_JFD_SALON',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_SATRAP_COURT',			'SND_BUILDING_JFD_SATRAP_COURT',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_SEAPORT',				'SND_BUILDING_JFD_SEAPORT',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_SHRINE',				'SND_BUILDING_JFD_SHRINE',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_SOLAR_PLANT',			'SND_BUILDING_JFD_SOLAR_PLANT',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_SPACESHIP',				'SND_BUILDING_JFD_SPACESHIP',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_STABLE',				'SND_BUILDING_JFD_STABLE',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_STADIUM',				'SND_BUILDING_JFD_STADIUM',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_STELE',					'SND_BUILDING_JFD_STELE',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_STOCK_EXCHANGE',		'SND_BUILDING_JFD_STOCK_EXCHANGE',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_STONEWORKS',			'SND_BUILDING_JFD_STONEWORKS',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_SUPERMARKET',			'SND_BUILDING_JFD_SUPERMARKET',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_TAVERN',				'SND_BUILDING_JFD_TAVERN',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_TEMPLE',				'SND_BUILDING_JFD_TEMPLE',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_THEATRE',				'SND_BUILDING_JFD_THEATRE',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_UNIVERSITY',			'SND_BUILDING_JFD_UNIVERSITY',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_VISITORS_CENTER',		'SND_BUILDING_JFD_VISITORS_CENTER',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_WALLS',					'SND_BUILDING_JFD_WALLS',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_WALLS_BABYLON',			'SND_BUILDING_JFD_WALLS_BABYLON',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_WAT',					'SND_BUILDING_JFD_WAT',					'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_WATERMILL',				'SND_BUILDING_JFD_WATERMILL',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_WEIGH_HOUSE',			'SND_BUILDING_JFD_WEIGH_HOUSE',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_WELL',					'SND_BUILDING_JFD_WELL',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_WIND_FARM',				'SND_BUILDING_JFD_WIND_FARM',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_WINDMILL',				'SND_BUILDING_JFD_WINDMILL',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_WRITERS_GUILD',			'SND_BUILDING_JFD_WRITERS_GUILD',		'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_WORKSHOP',				'SND_BUILDING_JFD_WORKSHOP',			'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_BUILDING_JFD_ZOO',					'SND_BUILDING_JFD_ZOO',					'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_UNIT_JFD_BUILD',						'SND_UNIT_JFD_BUILD',					'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_UNIT_JFD_BUILD_FIN',					'SND_UNIT_JFD_BUILD_FIN',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100),
		('AS2D_UNIT_JFD_PROMOTED',					'SND_UNIT_JFD_PROMOTED',				'GAME_SFX', 			1,						1,					-1.0,					100, 		100);			
--==========================================================================================================================
--==========================================================================================================================