--==========================================================================================================================
-- GREAT WORK CLASSES
--==========================================================================================================================
-- GreatWorkClasses
--------------------------------------------------------------------------------------------------------------------------	
INSERT INTO GreatWorkClasses
		(Type,							SlotType)
VALUES	('GREAT_WORK_JFD_FILM',			'GREAT_WORK_SLOT_JFD_FILM');
--==========================================================================================================================
-- GREAT WORK SLOTS
--==========================================================================================================================
-- GreatWorkClasses
--------------------------------------------------------------------------------------------------------------------------	
INSERT INTO GreatWorkSlots
		(Type,							SlotsToolTipText,									EmptyToolTipText, 										FilledIcon, 				EmptyIcon)
SELECT	'GREAT_WORK_SLOT_JFD_FILM',		'TXT_KEY_GREAT_WORK_SLOT_JFD_FILM_SLOTS_TOOLTIP',	'TXT_KEY_GREAT_WORK_SLOT_JFD_FILM_EMPTY_TOOLTIP',		'greatworks_film.dds',		'greatworks_film_empty.dds'
WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_PIT_PROGRESS_GREAT_PEOPLE_ADDITIONS_DIRECTOR' AND Value = 1);
--==========================================================================================================================
-- GREAT WORKS
--==========================================================================================================================
-- GreatWorks
--------------------------------------------------------------------------------------------------------------------------	
INSERT INTO GreatWorks
		(Type,									GreatWorkClassType,			Description,								EraType,			Audio, 										Image)
VALUES	('GREAT_WORK_JFD_MOTHERLAND_CALLS',		'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_MOTHERLAND_CALLS',	NULL,				'AS2D_GREAT_WORK_JFD_MOTHERLAND_CALLS',		'gwfmotherlandcalls.dds'),
		('GREAT_WORK_JFD_FILM_01',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_01',			'ERA_POSTMODERN',	'AS2D_GREAT_WORK_FILM_01',					'gwf01.dds'),
		('GREAT_WORK_JFD_FILM_02',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_02',			'ERA_POSTMODERN',	'AS2D_GREAT_WORK_FILM_02',					'gwf02.dds'),
		('GREAT_WORK_JFD_FILM_03',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_03',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_03',					'gwf03.dds'),
		('GREAT_WORK_JFD_FILM_04',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_04',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_04',					'gwf04.dds'),
		('GREAT_WORK_JFD_FILM_05',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_05',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_05',					'gwf05.dds'),
		('GREAT_WORK_JFD_FILM_06',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_06',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_06',					'gwf06.dds'),
		('GREAT_WORK_JFD_FILM_07',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_07',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_07',					'gwf07.dds'),
		('GREAT_WORK_JFD_FILM_08',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_08',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_08',					'gwf08.dds'),
		('GREAT_WORK_JFD_FILM_09',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_09',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_09',					'gwf09.dds'),
		('GREAT_WORK_JFD_FILM_10',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_10',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_10',					'gwf10.dds'),
		('GREAT_WORK_JFD_FILM_11',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_11',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_11',					'gwf11.dds'),
		('GREAT_WORK_JFD_FILM_12',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_12',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_12',					'gwf12.dds'),
		('GREAT_WORK_JFD_FILM_13',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_13',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_13',					'gwf13.dds'),
		('GREAT_WORK_JFD_FILM_14',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_14',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_14',					'gwf14.dds'),
		('GREAT_WORK_JFD_FILM_15',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_15',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_15',					'gwf15.dds'),
		('GREAT_WORK_JFD_FILM_16',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_16',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_16',					'gwf16.dds'),
		('GREAT_WORK_JFD_FILM_17',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_17',			'ERA_POSTMODERN',	'AS2D_GREAT_WORK_FILM_17',					'gwf17.dds'),
		('GREAT_WORK_JFD_FILM_18',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_18',			'ERA_POSTMODERN',	'AS2D_GREAT_WORK_FILM_18',					'gwf18.dds'),
		('GREAT_WORK_JFD_FILM_19',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_19',			'ERA_POSTMODERN',	'AS2D_GREAT_WORK_FILM_19',					'gwf19.dds'),
		('GREAT_WORK_JFD_FILM_20',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_20',			'ERA_POSTMODERN',	'AS2D_GREAT_WORK_FILM_20',					'gwf20.dds'),
		('GREAT_WORK_JFD_FILM_21',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_21',			'ERA_POSTMODERN',	'AS2D_GREAT_WORK_FILM_21',					'gwf21.dds'),
		('GREAT_WORK_JFD_FILM_22',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_22',			'ERA_POSTMODERN',	'AS2D_GREAT_WORK_FILM_22',					'gwf22.dds'),
		('GREAT_WORK_JFD_FILM_23',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_23',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_23',					'gwf23.dds'),
		('GREAT_WORK_JFD_FILM_24',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_24',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_24',					'gwf24.dds'),
		('GREAT_WORK_JFD_FILM_25',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_25',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_25',					'gwf25.dds'),
		('GREAT_WORK_JFD_FILM_26',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_26',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_26',					'gwf26.dds'),
		('GREAT_WORK_JFD_FILM_27',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_27',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_27',					'gwf27.dds'),
		('GREAT_WORK_JFD_FILM_28',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_28',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_28',					'gwf28.dds'),
		('GREAT_WORK_JFD_FILM_29',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_29',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_29',					'gwf29.dds'),
		('GREAT_WORK_JFD_FILM_30',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_30',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_30',					'gwf30.dds'),
		('GREAT_WORK_JFD_FILM_31',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_31',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_31',					'gwf31.dds'),
		('GREAT_WORK_JFD_FILM_32',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_32',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_32',					'gwf32.dds'),
		('GREAT_WORK_JFD_FILM_33',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_33',			'ERA_POSTMODERN',	'AS2D_GREAT_WORK_FILM_33',					'gwf33.dds'),
		('GREAT_WORK_JFD_FILM_34',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_34',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_34',					'gwf34.dds'),
		('GREAT_WORK_JFD_FILM_35',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_35',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_35',					'gwf35.dds'),
		('GREAT_WORK_JFD_FILM_36',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_36',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_36',					'gwf36.dds'),
		('GREAT_WORK_JFD_FILM_37',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_37',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_37',					'gwf37.dds'),
		('GREAT_WORK_JFD_FILM_38',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_38',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_38',					'gwf38.dds'),
		('GREAT_WORK_JFD_FILM_39',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_39',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_39',					'gwf39.dds'),
		('GREAT_WORK_JFD_FILM_40',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_40',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_40',					'gwf40.dds'),
		('GREAT_WORK_JFD_FILM_41',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_41',			'ERA_POSTMODERN',	'AS2D_GREAT_WORK_FILM_41',					'gwf41.dds'),
		('GREAT_WORK_JFD_FILM_42',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_42',			'ERA_FUTURE',		'AS2D_GREAT_WORK_FILM_42',					'gwf42.dds'),
		('GREAT_WORK_JFD_FILM_43',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_43',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_43',					'gwf43.dds'),
		('GREAT_WORK_JFD_FILM_44',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_44',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_44',					'gwf44.dds'),
		('GREAT_WORK_JFD_FILM_45',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_45',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_45',					'gwf45.dds'),
		('GREAT_WORK_JFD_FILM_46',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_46',			'ERA_FUTURE',		'AS2D_GREAT_WORK_FILM_46',					'gwf46.dds'),
		('GREAT_WORK_JFD_FILM_47',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_47',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_47',					'gwf47.dds'),
		('GREAT_WORK_JFD_FILM_48',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_48',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_48',					'gwf48.dds'),
		('GREAT_WORK_JFD_FILM_49',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_49',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_49',					'gwf49.dds'),
		('GREAT_WORK_JFD_FILM_50',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_50',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_50',					'gwf50.dds'),
		('GREAT_WORK_JFD_FILM_51',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_51',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_51',					'gwf51.dds'),
		('GREAT_WORK_JFD_FILM_52',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_52',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_52',					'gwf52.dds'),
		('GREAT_WORK_JFD_FILM_53',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_53',			'ERA_POSTMODERN',	'AS2D_GREAT_WORK_FILM_53',					'gwf53.dds'),
		('GREAT_WORK_JFD_FILM_54',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_54',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_54',					'gwf54.dds'),
		('GREAT_WORK_JFD_FILM_55',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_55',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_55',					'gwf55.dds'),
		('GREAT_WORK_JFD_FILM_56',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_56',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_56',					'gwf56.dds'),
		('GREAT_WORK_JFD_FILM_57',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_57',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_57',					'gwf57.dds'),
		('GREAT_WORK_JFD_FILM_58',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_58',			'ERA_FUTURE',		'AS2D_GREAT_WORK_FILM_58',					'gwf58.dds'),
		('GREAT_WORK_JFD_FILM_59',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_59',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_59',					'gwf59.dds'),
		('GREAT_WORK_JFD_FILM_60',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_60',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_60',					'gwf60.dds'),
		('GREAT_WORK_JFD_FILM_61',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_61',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_61',					'gwf61.dds'),
		('GREAT_WORK_JFD_FILM_62',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_62',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_62',					'gwf62.dds'),
		('GREAT_WORK_JFD_FILM_63',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_63',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_63',					'gwf63.dds'),
		('GREAT_WORK_JFD_FILM_64',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_64',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_64',					'gwf64.dds'),
		('GREAT_WORK_JFD_FILM_65',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_65',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_65',					'gwf65.dds'),
		('GREAT_WORK_JFD_FILM_66',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_66',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_66',					'gwf66.dds'),
		('GREAT_WORK_JFD_FILM_67',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_67',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_67',					'gwf67.dds'),
		('GREAT_WORK_JFD_FILM_68',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_68',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_68',					'gwf68.dds'),
		('GREAT_WORK_JFD_FILM_69',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_69',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_69',					'gwf69.dds'),
		('GREAT_WORK_JFD_FILM_70',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_70',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_70',					'gwf70.dds'),
		('GREAT_WORK_JFD_FILM_71',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_71',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_71',					'gwf71.dds'),
		('GREAT_WORK_JFD_FILM_72',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_72',			'ERA_POSTMODERN',	'AS2D_GREAT_WORK_FILM_72',					'gwf72.dds'),
		('GREAT_WORK_JFD_FILM_73',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_73',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_73',					'gwf73.dds'),
		('GREAT_WORK_JFD_FILM_74',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_74',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_74',					'gwf74.dds'),
		('GREAT_WORK_JFD_FILM_75',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_75',			'ERA_FUTURE',		'AS2D_GREAT_WORK_FILM_75',					'gwf75.dds'),
		('GREAT_WORK_JFD_FILM_76',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_76',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_76',					'gwf76.dds'),
		('GREAT_WORK_JFD_FILM_77',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_77',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_77',					'gwf77.dds'),
		('GREAT_WORK_JFD_FILM_78',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_78',			'ERA_POSTMODERN',	'AS2D_GREAT_WORK_FILM_78',					'gwf78.dds'),
		('GREAT_WORK_JFD_FILM_79',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_79',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_79',					'gwf79.dds'),
		('GREAT_WORK_JFD_FILM_80',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_80',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_80',					'gwf80.dds'),		
		('GREAT_WORK_JFD_FILM_81',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_81',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_81',					'gwf81.dds'),		
		('GREAT_WORK_JFD_FILM_82',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_82',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_82',					'gwf82.dds'),		
		('GREAT_WORK_JFD_FILM_83',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_83',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_83',					'gwf83.dds'),		
		('GREAT_WORK_JFD_FILM_84',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_84',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_84',					'gwf84.dds'),		
		('GREAT_WORK_JFD_FILM_85',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_85',			'ERA_POSTMODERN',	'AS2D_GREAT_WORK_FILM_85',					'gwf85.dds'),		
		('GREAT_WORK_JFD_FILM_86',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_86',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_86',					'gwf86.dds'),		
		('GREAT_WORK_JFD_FILM_87',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_87',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_87',					'gwf87.dds'),		
		('GREAT_WORK_JFD_FILM_88',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_88',			'ERA_POSTMODERN',	'AS2D_GREAT_WORK_FILM_88',					'gwf88.dds'),		
		('GREAT_WORK_JFD_FILM_89',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_89',			'ERA_FUTURE',		'AS2D_GREAT_WORK_FILM_89',					'gwf89.dds'),		
		('GREAT_WORK_JFD_FILM_90',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_90',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_90',					'gwf90.dds'),		
		('GREAT_WORK_JFD_FILM_91',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_91',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_91',					'gwf91.dds'),		
		('GREAT_WORK_JFD_FILM_92',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_92',			'ERA_FUTURE',		'AS2D_GREAT_WORK_FILM_92',					'gwf92.dds'),		
		('GREAT_WORK_JFD_FILM_93',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_93',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_93',					'gwf93.dds'),		
		('GREAT_WORK_JFD_FILM_94',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_94',			'ERA_FUTURE',		'AS2D_GREAT_WORK_FILM_94',					'gwf94.dds'),		
		('GREAT_WORK_JFD_FILM_95',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_95',			'ERA_FUTURE',		'AS2D_GREAT_WORK_FILM_95',					'gwf95.dds'),		
		('GREAT_WORK_JFD_FILM_96',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_96',			'ERA_FUTURE',		'AS2D_GREAT_WORK_FILM_96',					'gwf96.dds'),		
		('GREAT_WORK_JFD_FILM_97',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_97',			'ERA_FUTURE',		'AS2D_GREAT_WORK_FILM_97',					'gwf97.dds'),		
		('GREAT_WORK_JFD_FILM_98',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_98',			'ERA_FUTURE',		'AS2D_GREAT_WORK_FILM_98',					'gwf98.dds'),		
		('GREAT_WORK_JFD_FILM_99',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_99',			'ERA_MODERN',		'AS2D_GREAT_WORK_FILM_99',					'gwf99.dds'),		
		('GREAT_WORK_JFD_FILM_100',				'GREAT_WORK_JFD_FILM',		'TXT_KEY_GREAT_WORK_JFD_FILM_100',			'ERA_FUTURE',		'AS2D_GREAT_WORK_FILM_100',					'gwf100.dds');
--==========================================================================================================================
--==========================================================================================================================