--==========================================================================================================================
-- UNIT CLASSES
--==========================================================================================================================
-- UnitClasses
--------------------------------------------------------------------------------------------------------------------------	
--Airship
INSERT INTO UnitClasses
		(Type, 								DefaultUnit, 					Description)
SELECT	'UNITCLASS_JFD_AIRSHIP',			'UNIT_JFD_AIRSHIP', 			'TXT_KEY_UNIT_JFD_AIRSHIP'
WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_AIRSHIP' AND Value = 1);

--Adventurer
INSERT INTO UnitClasses
		(Type, 								DefaultUnit, 					Description)
SELECT	'UNITCLASS_JFD_ADVENTURER',			'UNIT_JFD_ADVENTURER', 			'TXT_KEY_JFD_ADVENTURER'	 
WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE' AND Value = 1);

--Explorer
INSERT INTO UnitClasses
		(Type, 								DefaultUnit, 					Description)
SELECT	'UNITCLASS_JFD_EXPLORER',			'UNIT_JFD_EXPLORER', 			'TXT_KEY_JFD_EXPLORER'	 
WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE' AND Value = 1);

--Great Adventurer
-- INSERT INTO UnitClasses
		-- (Type, 								DefaultUnit, 					Description)
-- SELECT	'UNITCLASS_JFD_GREAT_ADVENTURER',	'UNIT_JFD_GREAT_ADVENTURER', 	'TXT_KEY_JFD_GREAT_ADVENTURER' 
-- WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE' AND Value = 1);

-- UPDATE UnitClasses
-- SET JFD_GreatPersonUnitUpgrade = 'UNIT_JFD_GREAT_ADVENTURER'
-- WHERE Type = 'UNITCLASS_JFD_ADVENTURER'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

--Great Airship
-- INSERT INTO UnitClasses
		-- (Type, 								DefaultUnit, 					Description)
-- SELECT	'UNITCLASS_JFD_GREAT_AIRSHIP',		'UNIT_JFD_GREAT_AIRSHIP', 		'TXT_KEY_UNIT_JFD_GREAT_AIRSHIP' 
-- WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_AIRSHIP' AND Value = 1)
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

-- UPDATE UnitClasses
-- SET JFD_GreatPersonUnitUpgrade = 'UNIT_JFD_GREAT_AIRSHIP'
-- WHERE Type = 'UNITCLASS_JFD_AIRSHIP'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_AIRSHIP' AND Value = 1)
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

--Great Explorer
-- INSERT INTO UnitClasses
		-- (Type, 								DefaultUnit, 					Description)
-- SELECT	'UNITCLASS_JFD_GREAT_EXPLORER',		'UNIT_JFD_GREAT_EXPLORER', 		'TXT_KEY_JFD_GREAT_EXPLORER' 
-- WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

-- UPDATE UnitClasses
-- SET JFD_GreatPersonUnitUpgrade = 'UNIT_JFD_GREAT_EXPLORER'
-- WHERE Type = 'UNITCLASS_JFD_EXPLORER'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

--Great Scout
-- INSERT INTO UnitClasses
		-- (Type, 								DefaultUnit, 					Description)
-- SELECT	'UNITCLASS_JFD_GREAT_SCOUT',		'UNIT_JFD_GREAT_SCOUT', 		'TXT_KEY_JFD_GREAT_SCOUT'	 
-- WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

-- UPDATE UnitClasses
-- SET JFD_GreatPersonUnitUpgrade = 'UNIT_JFD_GREAT_SCOUT'
-- WHERE Type IN ('UNITCLASS_SCOUT', 'UNITCLASS_ARCHER')
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);
-------------------
-- Civilization_UnitClassOverrides
-------------------
-- INSERT INTO Civilization_UnitClassOverrides
		-- (CivilizationType, 			UnitClassType, 		UnitType)
-- SELECT	'CIVILIZATION_BARBARIAN',	Type, 				NULL
-- FROM UnitClasses WHERE Type IN ('UNITCLASS_JFD_GREAT_AIRSHIP', 'UNITCLASS_JFD_GREAT_ADVENTURER', 'UNITCLASS_JFD_GREAT_EXPLORER', 'UNITCLASS_JFD_GREAT_SCOUT')
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);
--==========================================================================================================================
-- UNITS
--==========================================================================================================================
-- Units
--------------------------------------------------------------------------------------------------------------------------	
--Adventurer
INSERT INTO Units
		(Class, 						Type,					PrereqTech, 				Combat, Cost, 	FaithCost, 	RequiresFaithPurchaseEnabled, Moves, CombatClass, Domain, DefaultUnitAI, Description, 				Civilopedia, 						Strategy, 							Help, 							ObsoleteTech, 				NoBadGoodies, Pillage, MilitarySupport, MilitaryProduction, AdvancedStartCost, XPValueAttack, XPValueDefense, UnitArtInfo, 						GoodyHutUpgradeUnitClass,	UnitFlagAtlas,	UnitFlagIconOffset, IconAtlas, 						PortraitIndex)
SELECT	'UNITCLASS_JFD_ADVENTURER', 	'UNIT_JFD_ADVENTURER', 	'TECH_SCIENTIFIC_THEORY', 	20, 	175, 	350, 		RequiresFaithPurchaseEnabled, 4,	 CombatClass, Domain, DefaultUnitAI, 'TXT_KEY_JFD_ADVENTURER', 	'TXT_KEY_JFD_ADVENTURER_PEDIA', 	'TXT_KEY_JFD_ADVENTURER_STRATEGY', 	'TXT_KEY_JFD_ADVENTURER_HELP', 	'TECH_RADIO',				NoBadGoodies, Pillage, MilitarySupport, MilitaryProduction, AdvancedStartCost, XPValueAttack, XPValueDefense, 'ART_DEF_UNIT_JFD_ADVENTURER',	GoodyHutUpgradeUnitClass,	UnitFlagAtlas,	UnitFlagIconOffset, 'JFD_EXPLORATION_UNIT_ATLAS',	4
FROM Units WHERE Type = 'UNIT_SCOUT'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE' AND Value = 1);

--Airship
INSERT INTO Units
		(Class, 						Type,					PrereqTech,					Combat, Cost, 	FaithCost, 	RequiresFaithPurchaseEnabled, Moves, CombatClass, Domain, DefaultUnitAI, Description, 				Civilopedia, 						Strategy, 							Help, 							ObsoleteTech, 				NoBadGoodies, Pillage, MilitarySupport, MilitaryProduction, AdvancedStartCost, XPValueAttack, XPValueDefense, UnitArtInfo, 						GoodyHutUpgradeUnitClass,	UnitFlagAtlas, UnitFlagIconOffset, IconAtlas, 						PortraitIndex, 	MoveRate)
SELECT	'UNITCLASS_JFD_AIRSHIP', 		'UNIT_JFD_AIRSHIP', 	'TECH_RADIO',				26, 	210, 	420, 		RequiresFaithPurchaseEnabled, 6, 	 CombatClass, Domain, DefaultUnitAI, 'TXT_KEY_JFD_AIRSHIP', 	'TXT_KEY_JFD_AIRSHIP_PEDIA', 		'TXT_KEY_JFD_AIRSHIP_STRATEGY', 	'TXT_KEY_JFD_AIRSHIP_HELP', 	'TECH_SATELLITES', 			NoBadGoodies, Pillage, MilitarySupport, MilitaryProduction, AdvancedStartCost, XPValueAttack, XPValueDefense, 'ART_DEF_UNIT_JFD_AIRSHIP',		GoodyHutUpgradeUnitClass,	UnitFlagAtlas, UnitFlagIconOffset, 'JFD_EXPLORATION_UNIT_ATLAS',	6,				'WHEELED'
FROM Units WHERE Type = 'UNIT_SCOUT'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_AIRSHIP' AND Value = 1);

UPDATE Units
SET GoodyHutUpgradeUnitClass = 'UNITCLASS_JFD_AIRSHIP'
WHERE Type = 'UNIT_JFD_ADVENTURER'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_AIRSHIP' AND Value = 1);

--Explorer
INSERT INTO Units
		(Class, 						Type,					PrereqTech, 				Combat, Cost, 	FaithCost, 	RequiresFaithPurchaseEnabled, Moves, CombatClass, Domain, DefaultUnitAI, Description, 				Civilopedia, 						Strategy, 							Help, 							ObsoleteTech, 				NoBadGoodies, Pillage, MilitarySupport, MilitaryProduction, AdvancedStartCost, XPValueAttack, XPValueDefense, UnitArtInfo, 						GoodyHutUpgradeUnitClass,	UnitFlagAtlas, UnitFlagIconOffset, 	IconAtlas, 						PortraitIndex)
SELECT	'UNITCLASS_JFD_EXPLORER', 		'UNIT_JFD_EXPLORER', 	'TECH_ASTRONOMY',			16, 	115, 	250, 		RequiresFaithPurchaseEnabled, 3,	 CombatClass, Domain, DefaultUnitAI, 'TXT_KEY_JFD_EXPLORER', 	'TXT_KEY_JFD_EXPLORER_PEDIA',		'TXT_KEY_JFD_EXPLORER_STRATEGY', 	'TXT_KEY_JFD_EXPLORER_HELP', 	'TECH_SCIENTIFIC_THEORY',	NoBadGoodies, Pillage, MilitarySupport, MilitaryProduction, AdvancedStartCost, XPValueAttack, XPValueDefense, 'ART_DEF_UNIT_JFD_EXPLORER', 		'UNITCLASS_JFD_ADVENTURER',	UnitFlagAtlas, UnitFlagIconOffset, 	'JFD_EXPLORATION_UNIT_ATLAS',	2
FROM Units WHERE Type = 'UNIT_SCOUT'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE' AND Value = 1);

--Scout
UPDATE Units
SET Help = 'TXT_KEY_JFD_SCOUT_HELP', Strategy = 'TXT_KEY_JFD_SCOUT_STRATEGY', IconAtlas = 'JFD_EXPLORATION_UNIT_ATLAS', PortraitIndex = 0
WHERE Type = 'UNIT_SCOUT'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE' AND Value = 1);

UPDATE Units
SET PrereqTech = 'TECH_TRAPPING'
WHERE Class = 'UNITCLASS_SCOUT'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_TECH_CHANGES_SCOUT' AND Value = 1);

--Great Adventurer
-- INSERT INTO Units
		-- (Class, 							Type,							PrereqTech, 	Special,				FoundAbroad, 	Combat, Cost, 	ShowInPedia,	FaithCost, 	PurchaseOnly,	MoveAfterPurchase,	Moves,	CombatClass, Domain, DefaultUnitAI,		Description, 						Strategy, 									Help, 									Civilopedia, 						ObsoleteTech, 	NoBadGoodies, Pillage, MilitarySupport, MilitaryProduction, AdvancedStartCost, XPValueAttack, XPValueDefense, UnitArtInfo, 							UnitFlagAtlas, 					UnitFlagIconOffset, IconAtlas, 						PortraitIndex)
-- SELECT	'UNITCLASS_JFD_GREAT_ADVENTURER', 	'UNIT_JFD_GREAT_ADVENTURER', 	PrereqTech, 	'SPECIALUNIT_PEOPLE',	1,				22, 	800, 	0,				0, 			1,				1,					4,		CombatClass, Domain, 'UNITAI_SETTLE',	'TXT_KEY_JFD_GREAT_ADVENTURER', 	'TXT_KEY_JFD_GREAT_ADVENTURER_STRATEGY', 	'TXT_KEY_JFD_GREAT_ADVENTURER_HELP', 	'TXT_KEY_JFD_ADVENTURER_PEDIA', 	'TECH_RADIO',	NoBadGoodies, Pillage, MilitarySupport, MilitaryProduction, AdvancedStartCost, XPValueAttack, XPValueDefense, 'ART_DEF_UNIT_JFD_GREAT_ADVENTURER', 	'EXPANSION2_UNIT_FLAG_ATLAS', 	5, 					'JFD_EXPLORATION_UNIT_ATLAS',	5
-- FROM Units WHERE Type = 'UNIT_JFD_ADVENTURER'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

-- UPDATE Units
-- SET GoodyHutUpgradeUnitClass = 'UNITCLASS_JFD_GREAT_AIRSHIP'
-- WHERE Type = 'UNIT_JFD_GREAT_ADVENTURER'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_AIRSHIP' AND Value = 1)
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

--Great Airship
-- INSERT INTO Units
		-- (Class, 						Type,							PrereqTech,		Special,				FoundAbroad, 	Combat, Cost, 	ShowInPedia,	FaithCost, 	 PurchaseOnly,	MoveAfterPurchase,	Moves, 	CombatClass, Domain, DefaultUnitAI,		Description, 					Strategy, 								Help, 								Civilopedia,					ObsoleteTech, 		NoBadGoodies, Pillage, MilitarySupport, MilitaryProduction, AdvancedStartCost, XPValueAttack, XPValueDefense, UnitArtInfo, 							UnitFlagAtlas, 					UnitFlagIconOffset, IconAtlas, 						PortraitIndex, 	MoveRate)
-- SELECT	'UNITCLASS_JFD_GREAT_AIRSHIP', 	'UNIT_JFD_GREAT_AIRSHIP', 		PrereqTech,		'SPECIALUNIT_PEOPLE',	1,				28, 	1000, 	0,				0,			 1,				1,					6, 		CombatClass, Domain, 'UNITAI_SETTLE',	'TXT_KEY_JFD_GREAT_AIRSHIP', 	'TXT_KEY_JFD_GREAT_AIRSHIP_STRATEGY', 	'TXT_KEY_JFD_GREAT_AIRSHIP_HELP', 	'TXT_KEY_JFD_AIRSHIP_PEDIA',	'TECH_SATELLITES', 	NoBadGoodies, Pillage, MilitarySupport, MilitaryProduction, AdvancedStartCost, XPValueAttack, XPValueDefense, 'ART_DEF_UNIT_JFD_GREAT_AIRSHIP', 	'EXPANSION2_UNIT_FLAG_ATLAS',	5, 					'JFD_EXPLORATION_UNIT_ATLAS', 7,				'WHEELED'
-- FROM Units WHERE Type = 'UNIT_JFD_AIRSHIP'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_AIRSHIP' AND Value = 1)
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

--Great Explorer
-- INSERT INTO Units
		-- (Class, 						Type,							PrereqTech, 	Special,				FoundAbroad, 	Combat, Cost, 	ShowInPedia,	FaithCost, 	PurchaseOnly,	MoveAfterPurchase,	Moves,	CombatClass, Domain, DefaultUnitAI,		Description, 					Strategy, 								Help, 								Civilopedia, 					ObsoleteTech, 				NoBadGoodies, Pillage, MilitarySupport, MilitaryProduction, AdvancedStartCost, XPValueAttack, XPValueDefense, UnitArtInfo, 							UnitFlagAtlas, 					UnitFlagIconOffset, IconAtlas, 						PortraitIndex)
-- SELECT	'UNITCLASS_JFD_GREAT_EXPLORER', 'UNIT_JFD_GREAT_EXPLORER', 		PrereqTech,		'SPECIALUNIT_PEOPLE',	1,				18, 	600, 	0,				0, 			1,				1,					3,		CombatClass, Domain, 'UNITAI_SETTLE',	'TXT_KEY_JFD_GREAT_EXPLORER',	'TXT_KEY_JFD_GREAT_EXPLORER_STRATEGY', 	'TXT_KEY_JFD_GREAT_EXPLORER_HELP', 	'TXT_KEY_JFD_EXPLORER_PEDIA',	'TECH_SCIENTIFIC_THEORY',	NoBadGoodies, Pillage, MilitarySupport, MilitaryProduction, AdvancedStartCost, XPValueAttack, XPValueDefense, 'ART_DEF_UNIT_JFD_GREAT_EXPLORER', 	'EXPANSION2_UNIT_FLAG_ATLAS',	5, 					'JFD_EXPLORATION_UNIT_ATLAS',	3
-- FROM Units WHERE Type = 'UNIT_JFD_EXPLORER'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

-- UPDATE Units
-- SET GoodyHutUpgradeUnitClass = 'UNITCLASS_JFD_GREAT_ADVENTURER'
-- WHERE Type = 'UNIT_JFD_GREAT_EXPLORER'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

--Great Scout
-- INSERT INTO Units
		-- (Class, 						Type,						PrereqTech, 		Special,				FoundAbroad, 	Combat, Cost, 	ShowInPedia,	FaithCost, 	PurchaseOnly,	MoveAfterPurchase,	Moves,	CombatClass, Domain, DefaultUnitAI,		Description, 					Strategy, 								Help, 								Civilopedia, ObsoleteTech, 		NoBadGoodies, Pillage, MilitarySupport, MilitaryProduction, AdvancedStartCost, XPValueAttack, XPValueDefense, UnitArtInfo, 						UnitFlagAtlas, 					UnitFlagIconOffset, IconAtlas, 						PortraitIndex)
-- SELECT	'UNITCLASS_JFD_GREAT_SCOUT', 	'UNIT_JFD_GREAT_SCOUT', 	'TECH_TRAPPING', 	'SPECIALUNIT_PEOPLE',	1,				7, 		300, 	0,				0, 			1,				1,					2,		CombatClass, Domain, 'UNITAI_SETTLE',	'TXT_KEY_JFD_GREAT_SCOUT',		'TXT_KEY_JFD_GREAT_SCOUT_STRATEGY', 	'TXT_KEY_JFD_GREAT_SCOUT_HELP', 	Civilopedia, 'TECH_ASTRONOMY',	NoBadGoodies, Pillage, MilitarySupport, MilitaryProduction, AdvancedStartCost, XPValueAttack, XPValueDefense, 'ART_DEF_UNIT_JFD_GREAT_SCOUT',	'EXPANSION2_UNIT_FLAG_ATLAS',	5, 					'JFD_EXPLORATION_UNIT_ATLAS',	1
-- FROM Units WHERE Type = 'UNIT_SCOUT'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

-- UPDATE Units
-- SET GoodyHutUpgradeUnitClass = 'UNITCLASS_JFD_GREAT_EXPLORER'
-- WHERE Type = 'UNIT_JFD_GREAT_SCOUT'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

--Admiral
-- UPDATE Units
-- SET Strategy = 'TXT_KEY_UNIT_JFD_GREAT_ADMIRAL_STRATEGY'
-- WHERE Type = 'UNIT_GREAT_ADMIRAL'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_CHANGES_ADMIRAL' AND Value = 1);

-- UPDATE Units
-- SET NumFreeLux = 2
-- WHERE Class = 'UNITCLASS_GREAT_ADMIRAL'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_CHANGES_ADMIRAL' AND Value = 1);

-- CREATE TRIGGER JFDExCE_Units_Admirals
-- AFTER INSERT ON Units 
-- WHEN NEW.Class = 'UNITCLASS_GREAT_ADMIRAL'
-- BEGIN
	-- UPDATE Units
	-- SET NumFreeLux = 2
	-- WHERE Type = NEW.Type
	-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_CHANGES_ADMIRAL' AND Value = 1);
-- END;

--Triremes
UPDATE Units
SET Moves = Moves-1
WHERE Class = 'UNITCLASS_TRIREME'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_CHANGES_TRIREME' AND Value = 1);

--JFDExCE_Exploration_Units
CREATE TRIGGER JFDExCE_Exploration_Units
AFTER INSERT ON Units 
WHEN NEW.Class IN ('UNITCLASS_SCOUT', 'UNITCLASS_TRIREME')
BEGIN
	UPDATE Units
	SET PrereqTech = 'TECH_TRAPPING'
	WHERE Type = NEW.Type AND NEW.Class = 'UNITCLASS_SCOUT'
	AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_TECH_CHANGES_SCOUT' AND Value = 1);
	
	UPDATE Units
	SET Moves = Moves-1
	WHERE Type = NEW.Type AND NEW.Class = 'UNITCLASS_TRIREME'
	AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_CHANGES_TRIREME' AND Value = 1);
END;
--------------------------------------------------------------------------------------------------------------------------
-- Unit_AITypes
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Unit_AITypes
		(UnitType,						UnitAIType)
SELECT	'UNIT_JFD_ADVENTURER', 			UnitAIType
FROM Unit_AITypes WHERE UnitType = 'UNIT_SCOUT'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE' AND Value = 1);

INSERT INTO Unit_AITypes
		(UnitType,						UnitAIType)
SELECT	'UNIT_JFD_AIRSHIP', 			UnitAIType
FROM Unit_AITypes WHERE UnitType = 'UNIT_SCOUT'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_AIRSHIP' AND Value = 1);

INSERT INTO Unit_AITypes
		(UnitType,						UnitAIType)
SELECT	'UNIT_JFD_EXPLORER', 			UnitAIType
FROM Unit_AITypes WHERE UnitType = 'UNIT_SCOUT'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE' AND Value = 1);

-- INSERT INTO Unit_AITypes
		-- (UnitType,						UnitAIType)
-- SELECT	'UNIT_JFD_GREAT_ADVENTURER', 	UnitAIType
-- FROM Unit_AITypes WHERE UnitType IN ('UNIT_SCOUT', 'UNIT_SETTLER')
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

-- INSERT INTO Unit_AITypes
		-- (UnitType,						UnitAIType)
-- SELECT	'UNIT_JFD_GREAT_AIRSHIP', 		UnitAIType
-- FROM Unit_AITypes WHERE UnitType IN ('UNIT_SCOUT', 'UNIT_SETTLER')
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_AIRSHIP' AND Value = 1)
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

-- INSERT INTO Unit_AITypes
		-- (UnitType,						UnitAIType)
-- SELECT	'UNIT_JFD_GREAT_EXPLORER', 		UnitAIType
-- FROM Unit_AITypes WHERE UnitType IN ('UNIT_SCOUT', 'UNIT_SETTLER')
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

-- INSERT INTO Unit_AITypes
		-- (UnitType,						UnitAIType)
-- SELECT	'UNIT_JFD_GREAT_SCOUT', 		UnitAIType
-- FROM Unit_AITypes WHERE UnitType IN ('UNIT_SCOUT', 'UNIT_SETTLER')
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);
--------------------------------------------------------------------------------------------------------------------------	
-- UnitGameplay2DScripts
--------------------------------------------------------------------------------------------------------------------------		
INSERT INTO UnitGameplay2DScripts 	
		(UnitType, 						SelectionSound, FirstSelectionSound)
SELECT	'UNIT_JFD_ADVENTURER', 			SelectionSound, FirstSelectionSound
FROM UnitGameplay2DScripts WHERE UnitType = 'UNIT_SCOUT'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE' AND Value = 1);

INSERT INTO UnitGameplay2DScripts 	
		(UnitType, 						SelectionSound, FirstSelectionSound)
SELECT	'UNIT_JFD_EXPLORER', 			SelectionSound, FirstSelectionSound
FROM UnitGameplay2DScripts WHERE UnitType = 'UNIT_SCOUT'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE' AND Value = 1);

-- INSERT INTO UnitGameplay2DScripts 	
		-- (UnitType, 						SelectionSound, FirstSelectionSound)
-- SELECT	'UNIT_JFD_GREAT_ADVENTURER', 	SelectionSound, FirstSelectionSound
-- FROM UnitGameplay2DScripts WHERE UnitType = 'UNIT_SCOUT'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

-- INSERT INTO UnitGameplay2DScripts 	
		-- (UnitType, 						SelectionSound, FirstSelectionSound)
-- SELECT	'UNIT_JFD_GREAT_EXPLORER', 		SelectionSound, FirstSelectionSound
-- FROM UnitGameplay2DScripts WHERE UnitType = 'UNIT_SCOUT'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

-- INSERT INTO UnitGameplay2DScripts 	
		-- (UnitType, 						SelectionSound, FirstSelectionSound)
-- SELECT	'UNIT_JFD_GREAT_SCOUT', 		SelectionSound, FirstSelectionSound
-- FROM UnitGameplay2DScripts WHERE UnitType = 'UNIT_SCOUT'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);
--------------------------------------------------------------------------------------------------------------------------
-- Unit_UniqueNames
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Unit_UniqueNames
		(UnitType,                          UniqueName)
VALUES  ('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_1'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_2'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_3'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_4'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_5'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_6'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_7'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_8'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_9'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_10'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_11'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_12'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_13'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_14'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_15'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_16'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_17'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_18'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_19'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_20'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_21'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_22'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_23'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_24'),
		('UNIT_SPANISH_CONQUISTADOR',   	'TXT_KEY_GREAT_PERSON_JFD_CONQUISTADOR_25');
				 
INSERT INTO Unit_UniqueNames
		(UnitType, 						UniqueName)
VALUES	('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_1'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_2'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_3'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_4'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_5'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_6'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_7'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_8'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_9'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_10'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_11'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_12'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_13'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_14'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_15'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_16'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_17'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_18'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_19'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_20'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_21'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_22'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_23'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_24'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_25'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_26'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_27'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_28'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_29'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_30'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_31'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_32'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_33'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_34'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_35'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_36'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_37'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_38'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_39'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_40'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_41'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_42'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_43'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_44'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_45'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_46'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_47'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_48'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_49'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_50'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_51'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_52'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_53'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_54'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_55'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_56'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_57'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_58'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_59'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_60'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_61'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_62'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_63'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_64'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_65'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_66'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_67'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_68'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_69'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_70'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_71'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_72'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_73'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_74'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_75'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_76'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_77'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_78'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_79'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_80'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_81'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_82'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_83'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_84'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_85'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_86'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_87'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_88'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_89'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_90');
			
DELETE FROM Unit_UniqueNames WHERE UnitType IN ('UNIT_GREAT_ADMIRAL', 'UNIT_GREAT_GENERAL', 'UNIT_MERCHANT');			
INSERT INTO Unit_UniqueNames
		(UnitType, 						UniqueName)
VALUES	('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_1'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_2'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_3'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_4'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_5'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_6'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_7'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_8'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_9'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_10'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_11'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_12'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_13'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_14'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_15'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_16'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_17'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_18'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_19'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_20'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_21'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_22'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_23'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_24'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_25'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_26'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_27'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_28'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_29'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_30'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_31'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_32'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_33'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_34'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_35'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_36'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_37'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_38'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_39'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_40'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_41'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_42'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_43'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_44'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_45'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_46'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_47'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_48'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_49'),
		('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_1'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_2'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_3'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_4'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_5'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_6'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_7'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_8'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_9'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_10'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_11'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_12'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_13'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_14'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_15'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_16'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_17'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_18'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_19'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_20'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_21'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_22'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_23'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_24'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_25'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_26'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_27'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_28'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_29'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_30'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_31'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_32'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_33'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_34'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_35'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_36'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_37'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_38'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_39'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_40'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_41'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_42'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_43'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_44'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_45'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_46'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_47'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_48'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_49'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_50'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_51'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_52'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_53'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_54'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_55'),
		('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_56'),
		('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_57'),
		('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_1'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_2'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_3'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_4'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_5'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_6'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_7'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_8'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_9'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_10'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_11'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_12'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_13'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_14'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_15'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_16'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_17'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_18'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_19'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_20'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_21'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_22'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_23'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_24'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_25'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_26'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_27'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_28'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_29'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_30'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_31'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_32'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_33'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_34'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_35'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_36'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_37'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_38'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_39'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_40'),
		('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_41'),
		('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_42'),
		('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_43'),
		('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_44'),
		('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_45'),
		('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_46'),
		('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_47'),
		('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_48'),
		('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_49');

INSERT INTO Unit_UniqueNames
		(UnitType,						UniqueName)
SELECT	'UNIT_JFD_ADVENTURER',			UniqueName
FROM Unit_UniqueNames WHERE UnitType = 'UNIT_SCOUT'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE' AND Value = 1);

INSERT INTO Unit_UniqueNames
		(UnitType,						UniqueName)
SELECT	'UNIT_JFD_AIRSHIP',				UniqueName
FROM Unit_UniqueNames WHERE UnitType = 'UNIT_SCOUT'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_AIRSHIP' AND Value = 1);

INSERT INTO Unit_UniqueNames
		(UnitType,						UniqueName)
SELECT	'UNIT_JFD_EXPLORER',			UniqueName
FROM Unit_UniqueNames WHERE UnitType = 'UNIT_SCOUT'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE' AND Value = 1);

-- INSERT INTO Unit_UniqueNames
		-- (UnitType,						UniqueName)
-- SELECT	'UNIT_JFD_GREAT_ADVENTURER',	UniqueName
-- FROM Unit_UniqueNames WHERE UnitType = 'UNIT_SCOUT'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

-- INSERT INTO Unit_UniqueNames
		-- (UnitType,						UniqueName)
-- SELECT	'UNIT_JFD_GREAT_AIRSHIP',		UniqueName
-- FROM Unit_UniqueNames WHERE UnitType = 'UNIT_SCOUT'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_AIRSHIP' AND Value = 1)
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

-- INSERT INTO Unit_UniqueNames
		-- (UnitType,						UniqueName)
-- SELECT	'UNIT_JFD_GREAT_EXPLORER',		UniqueName
-- FROM Unit_UniqueNames WHERE UnitType = 'UNIT_SCOUT'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

-- INSERT INTO Unit_UniqueNames
		-- (UnitType,						UniqueName)
-- SELECT	'UNIT_JFD_GREAT_SCOUT',			UniqueName
-- FROM Unit_UniqueNames WHERE UnitType = 'UNIT_SCOUT'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);
--------------------------------------------------------------------------------------------------------------------------
-- Unit_Flavors
-----------------------------------------------------------------------------------------------------------------------------
INSERT INTO Unit_Flavors
		(UnitType,						FlavorType, Flavor)
SELECT	'UNIT_JFD_ADVENTURER', 			FlavorType, 40
FROM Unit_Flavors WHERE UnitType = 'UNIT_SCOUT'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE' AND Value = 1);

INSERT INTO Unit_Flavors
		(UnitType,						FlavorType, Flavor)
SELECT	'UNIT_JFD_AIRSHIP', 			FlavorType, 50
FROM Unit_Flavors WHERE UnitType = 'UNIT_SCOUT'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_AIRSHIP' AND Value = 1);

INSERT INTO Unit_Flavors
		(UnitType,						FlavorType, Flavor)
SELECT	'UNIT_JFD_EXPLORER', 			FlavorType, 25
FROM Unit_Flavors WHERE UnitType = 'UNIT_SCOUT'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE' AND Value = 1);

-- INSERT INTO Unit_Flavors
		-- (UnitType,						FlavorType, Flavor)
-- SELECT	'UNIT_JFD_GREAT_ADVENTURER',	FlavorType, 40
-- FROM Unit_Flavors WHERE UnitType = 'UNIT_SCOUT'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

-- INSERT INTO Unit_Flavors
		-- (UnitType,						FlavorType, Flavor)
-- SELECT	'UNIT_JFD_GREAT_AIRSHIP', 		FlavorType, 50
-- FROM Unit_Flavors WHERE UnitType = 'UNIT_SCOUT'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_AIRSHIP' AND Value = 1)
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

-- INSERT INTO Unit_Flavors
		-- (UnitType,						FlavorType, Flavor)
-- SELECT	'UNIT_JFD_GREAT_EXPLORER', 		FlavorType, 25
-- FROM Unit_Flavors WHERE UnitType = 'UNIT_SCOUT'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

-- INSERT INTO Unit_Flavors
		-- (UnitType,						FlavorType, Flavor)
-- SELECT	'UNIT_JFD_GREAT_SCOUT', 		FlavorType, Flavor
-- FROM Unit_Flavors WHERE UnitType = 'UNIT_SCOUT'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);
--------------------------------------------------------------------------------------------------------------------------
-- Unit_ClassUpgrades
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Unit_ClassUpgrades
		(UnitType,					UnitClassType)
SELECT	'UNIT_JFD_ADVENTURER', 		'UNITCLASS_JFD_AIRSHIP'
WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_AIRSHIP' AND Value = 1);

INSERT INTO Unit_ClassUpgrades
		(UnitType,					UnitClassType)
SELECT	'UNIT_JFD_EXPLORER', 		'UNITCLASS_JFD_ADVENTURER'
WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE' AND Value = 1);

INSERT INTO Unit_ClassUpgrades
		(UnitType,		UnitClassType)
SELECT	Type, 			'UNITCLASS_JFD_EXPLORER'
FROM Units WHERE Class = 'UNITCLASS_SCOUT'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE' AND Value = 1);

CREATE TRIGGER JFDExCE_Exploration_Unit_ClassUpgradesScout
AFTER INSERT ON Units 
WHEN NEW.Class = 'UNITCLASS_SCOUT'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE' AND Value = 1)
BEGIN
	INSERT INTO Unit_ClassUpgrades
			(UnitType, 				UnitClassType)
	VALUES	(NEW.Type,				'UNITCLASS_JFD_EXPLORER');
END;

-- INSERT INTO Unit_ClassUpgrades
		-- (UnitType,					UnitClassType)
-- SELECT	'UNIT_JFD_GREAT_ADVENTURER','UNITCLASS_JFD_GREAT_AIRSHIP'
-- WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_AIRSHIP' AND Value = 1)
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

-- INSERT INTO Unit_ClassUpgrades
		-- (UnitType,					UnitClassType)
-- SELECT	'UNIT_JFD_GREAT_EXPLORER', 	'UNITCLASS_JFD_GREAT_ADVENTURER'
-- WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

-- INSERT INTO Unit_ClassUpgrades
		-- (UnitType,					UnitClassType)
-- SELECT	'UNIT_JFD_GREAT_SCOUT', 	'UNITCLASS_JFD_GREAT_EXPLORER'
-- WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);
--------------------------------------------------------------------------------------------------------------------------
-- Unit_FreePromotions
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Unit_FreePromotions
		(UnitType,			PromotionType)
SELECT	Type, 				'PROMOTION_JFD_RECON_XP'
FROM Units WHERE Class = 'UNITCLASS_SCOUT'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_PROMOTION_ADDITIONS' AND Value = 1);

INSERT INTO Unit_FreePromotions
		(UnitType,					 PromotionType)
SELECT	Type,						'PROMOTION_JFD_RECON_XP'
FROM Units WHERE Class = 'UNITCLASS_CARAVEL'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_CHANGES_CARAVEL' AND Value = 1);

-- INSERT INTO Unit_FreePromotions
		-- (UnitType,			PromotionType)
-- SELECT	Type, 				'PROMOTION_JFD_GREAT_RECON'
-- FROM Units WHERE Class = 'UNITCLASS_SCOUT'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

CREATE TRIGGER JFDExCE_Exploration_Unit_FreePromotions
AFTER INSERT ON Units 
WHEN NEW.Class IN ('UNITCLASS_SCOUT', 'UNITCLASS_CARAVEL')
BEGIN
	INSERT INTO Unit_FreePromotions
			(UnitType, 		PromotionType)
	SELECT	NEW.Type,		'PROMOTION_JFD_RECON_XP'
	WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_PROMOTION_ADDITIONS' AND Value = 1);
	
	-- INSERT INTO Unit_FreePromotions
			-- (UnitType, 		PromotionType)
	-- SELECT	NEW.Type,		'PROMOTION_JFD_GREAT_RECON'
	-- WHERE EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);
END;
	
INSERT INTO Unit_FreePromotions
		(UnitType,					PromotionType)
SELECT	'UNIT_JFD_ADVENTURER', 		Type
FROM UnitPromotions WHERE Type IN ('PROMOTION_JFD_GREAT_RECON', 'PROMOTION_JFD_RECON_XP', 'PROMOTION_IGNORE_TERRAIN_COST', 'PROMOTION_SURVIVALISM_1', 'PROMOTION_SURVIVALISM_2')
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE' AND Value = 1);
	
INSERT INTO Unit_FreePromotions
		(UnitType,					PromotionType)
SELECT	'UNIT_JFD_AIRSHIP', 		Type
FROM UnitPromotions WHERE Type IN ('PROMOTION_SURVIVALISM_1', 'PROMOTION_JFD_RECON_XP', 'PROMOTION_SURVIVALISM_2', 'PROMOTION_HOVERING_UNIT')
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_AIRSHIP' AND Value = 1);

INSERT INTO Unit_FreePromotions
		(UnitType,					PromotionType)
SELECT	'UNIT_JFD_EXPLORER', 		Type
FROM UnitPromotions WHERE Type IN ('PROMOTION_JFD_GREAT_RECON', 'PROMOTION_JFD_RECON_XP', 'PROMOTION_IGNORE_TERRAIN_COST', 'PROMOTION_SURVIVALISM_1')
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE' AND Value = 1);
		
-- INSERT INTO Unit_FreePromotions
		-- (UnitType,					PromotionType)
-- SELECT	'UNIT_JFD_GREAT_SCOUT', 	Type
-- FROM UnitPromotions WHERE Type IN ('PROMOTION_JFD_GREAT_RECON_UNIT', 'PROMOTION_JFD_RECON_XP', 'PROMOTION_IGNORE_TERRAIN_COST')
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

-- INSERT INTO Unit_FreePromotions
		-- (UnitType,					PromotionType)
-- SELECT	'UNIT_JFD_GREAT_EXPLORER', 	Type
-- FROM UnitPromotions WHERE Type IN ('PROMOTION_JFD_GREAT_RECON_UNIT', 'PROMOTION_JFD_RECON_XP', 'PROMOTION_IGNORE_TERRAIN_COST', 'PROMOTION_SURVIVALISM_1')
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

-- INSERT INTO Unit_FreePromotions
		-- (UnitType,					PromotionType)
-- SELECT	'UNIT_JFD_GREAT_ADVENTURER',Type
-- FROM UnitPromotions WHERE Type IN ('PROMOTION_JFD_GREAT_RECON_UNIT', 'PROMOTION_JFD_RECON_XP', 'PROMOTION_IGNORE_TERRAIN_COST', 'PROMOTION_SURVIVALISM_1', 'PROMOTION_SURVIVALISM_2')
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

-- INSERT INTO Unit_FreePromotions
		-- (UnitType,					PromotionType)
-- SELECT	'UNIT_JFD_GREAT_AIRSHIP',	Type
-- FROM UnitPromotions WHERE Type IN ('PROMOTION_JFD_GREAT_RECON_UNIT', 'PROMOTION_JFD_RECON_XP', 'PROMOTION_IGNORE_TERRAIN_COST', 'PROMOTION_SURVIVALISM_1', 'PROMOTION_SURVIVALISM_2', 'PROMOTION_HOVERING_UNIT')
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_AIRSHIP' AND Value = 1)
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_ADDITIONS_RECON_LINE_GREAT_RECON' AND Value = 1);

-- INSERT INTO Unit_FreePromotions
		-- (UnitType,					 PromotionType)
-- SELECT	'UNIT_SPANISH_CONQUISTADOR', PromotionType
-- FROM Unit_FreePromotions WHERE UnitType = 'UNIT_JFD_GREAT_EXPLORER'
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_UNIT_CHANGES_CONQUSITADOR' AND Value = 1);
--==========================================================================================================================	
-- REMAPPER
--==========================================================================================================================	
CREATE TABLE IDRemapper ( id INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT );
INSERT INTO IDRemapper (Type) SELECT Type FROM Missions ORDER BY ID;
UPDATE Missions SET ID = ( SELECT IDRemapper.id-1 FROM IDRemapper WHERE Missions.Type = IDRemapper.Type);
DROP TABLE IDRemapper;
--==========================================================================================================================
--==========================================================================================================================		
		
			