--==========================================================================================================================
-- GAZEBO COMMUNITY BALANCE PATCH
--==========================================================================================================================
-- Buildings
------------------------
UPDATE Buildings
SET Help = 'TXT_KEY_BUILDING_JFD_BASILICA_HELP_CBP'
WHERE Type = 'BUILDING_BASILICA'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

UPDATE Buildings
SET Help = 'TXT_KEY_BUILDING_JFD_BASILICA_HELP_CBP_MORE_LUX'
WHERE Type = 'BUILDING_BASILICA'
AND EXISTS (SELECT Type FROM Resources WHERE Type = 'RESOURCE_AMBER')
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

UPDATE Buildings
SET Help = 'TXT_KEY_BUILDING_JFD_BAZAAR_HELP_CBP', Strategy = 'TXT_KEY_BUILDING_JFD_BAZAAR_STRATEGY_CBP'
WHERE Type = 'BUILDING_BAZAAR'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

UPDATE Buildings
SET Help = 'TXT_KEY_BUILDING_JFD_CANDI_HELP_CBP'
WHERE Type = 'BUILDING_CANDI'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

UPDATE Buildings
SET Help = 'TXT_KEY_BUILDING_JFD_HERBALIST_HELP_CBP'
WHERE Type = 'BUILDING_HERBALIST'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

UPDATE Buildings
SET Help = 'TXT_KEY_BUILDING_JFD_FACTORY_HELP_CBP'
WHERE Type = 'BUILDING_FACTORY'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_BUILDING_CHANGES_FACTORY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_BONUS' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

UPDATE Buildings
SET Help = 'TXT_KEY_BUILDING_JFD_GARDEN_HELP_CBP'
WHERE Type = 'BUILDING_GARDEN'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

UPDATE Buildings
SET Help = 'TXT_KEY_BUILDING_JFD_LONGHOUSE_HELP_CBP'
WHERE Type = 'BUILDING_LONGHOUSE'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

UPDATE Buildings
SET Help = 'TXT_KEY_BUILDING_JFD_MARKET_HELP_CBP'
WHERE Type = 'BUILDING_MARKET'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

UPDATE Buildings
SET Help = 'TXT_KEY_BUILDING_JFD_TEMPLE_HELP_CBP'
WHERE Type = 'BUILDING_TEMPLE'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

UPDATE Buildings
SET Help = 'TXT_KEY_BUILDING_JFD_TEMPLE_HELP_CBP_MORE_LUX'
WHERE Type = 'BUILDING_TEMPLE'
AND EXISTS (SELECT Type FROM Resources WHERE Type = 'RESOURCE_AMBER')
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

UPDATE Buildings
SET Help = 'TXT_KEY_BUILDING_JFD_STEAM_MILL_HELP_CBP'
WHERE Type = 'BUILDING_STEAM_MILL'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_BUILDING_CHANGES_FACTORY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_BONUS' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);
------------------------
-- Building_ResourceYieldChanges
------------------------
INSERT INTO Building_ResourceYieldChanges
		(BuildingType,	ResourceType, 				YieldType,				Yield)
SELECT	Type,			'RESOURCE_JFD_OPIUM',		'YIELD_GOLD', 			1
FROM Buildings WHERE BuildingClass = 'BUILDINGCLASS_BATH'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

INSERT INTO Building_ResourceYieldChanges
		(BuildingType,	ResourceType, 				YieldType,				Yield)
SELECT	Type,			'RESOURCE_JFD_OPIUM',		'YIELD_FOOD', 			1
FROM Buildings WHERE BuildingClass = 'BUILDINGCLASS_BATH'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

INSERT INTO Building_ResourceYieldChanges
		(BuildingType,	ResourceType, 				YieldType,				Yield)
SELECT	Type,			'RESOURCE_JFD_OPIUM',		'YIELD_FOOD', 			1
FROM Buildings WHERE BuildingClass = 'BUILDINGCLASS_GARDEN'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

INSERT INTO Building_ResourceYieldChanges
		(BuildingType,	ResourceType, 				YieldType,				Yield)
SELECT	Type,			'RESOURCE_JFD_OPIUM',		'YIELD_FOOD', 			1
FROM Buildings WHERE BuildingClass = 'BUILDINGCLASS_GARDEN'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

INSERT INTO Building_ResourceYieldChanges
		(BuildingType,	ResourceType, 				YieldType,				Yield)
SELECT	Type,			'RESOURCE_JFD_OBSIDIAN',	'YIELD_GOLD', 			1
FROM Buildings WHERE BuildingClass = 'BUILDINGCLASS_HERBALIST'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

INSERT INTO Building_ResourceYieldChanges
		(BuildingType,	ResourceType, 				YieldType,				Yield)
SELECT	Type,			'RESOURCE_JFD_OBSIDIAN',	'YIELD_PRODUCTION', 	1
FROM Buildings WHERE BuildingClass = 'BUILDINGCLASS_HERBALIST'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

INSERT INTO Building_ResourceYieldChanges
		(BuildingType,	ResourceType, 				YieldType,				Yield)
SELECT	Type,			'RESOURCE_JFD_VANILLA',		'YIELD_GOLD', 			1
FROM Buildings WHERE BuildingClass = 'BUILDINGCLASS_HERBALIST'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

INSERT INTO Building_ResourceYieldChanges
		(BuildingType,	ResourceType, 				YieldType,				Yield)
SELECT	Type,			'RESOURCE_JFD_VANILLA',		'YIELD_FOOD', 			1
FROM Buildings WHERE BuildingClass = 'BUILDINGCLASS_HERBALIST'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

INSERT INTO Building_ResourceYieldChanges
		(BuildingType,	ResourceType, 				YieldType,				Yield)
SELECT	Type,			'RESOURCE_JFD_GINGER',		'YIELD_GOLD', 			1
FROM Buildings WHERE BuildingClass = 'BUILDINGCLASS_MARKET'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

INSERT INTO Building_ResourceYieldChanges
		(BuildingType,	ResourceType, 				YieldType,				Yield)
SELECT	Type,			'RESOURCE_JFD_GINGER',		'YIELD_FAITH', 			1
FROM Buildings WHERE BuildingClass = 'BUILDINGCLASS_MARKET'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

INSERT INTO Building_ResourceYieldChanges
		(BuildingType,	ResourceType, 				YieldType,				Yield)
SELECT	Type,			'RESOURCE_JFD_SAFFRON',		'YIELD_CULTURE', 		1
FROM Buildings WHERE BuildingClass = 'BUILDINGCLASS_TEMPLE'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

INSERT INTO Building_ResourceYieldChanges
		(BuildingType,	ResourceType, 				YieldType,				Yield)
SELECT	Type,			'RESOURCE_JFD_SAFFRON',		'YIELD_FAITH', 			1
FROM Buildings WHERE BuildingClass = 'BUILDINGCLASS_TEMPLE'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);
------------------------
-- Units
------------------------
UPDATE Units
SET PrereqTech = NULL, Cost = -1, ShowInPedia = 0
WHERE Type IN ('UNIT_EXPLORER', 'UNIT_ADVENTURER')
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

-- UPDATE Units
-- SET HurryCostModifier = -1
-- WHERE Type IN ('UNIT_JFD_GREAT_SCOUT', 'UNIT_JFD_GREAT_EXPLORER', 'UNIT_JFD_GREAT_ADVENTURER', 'UNIT_JFD_GREAT_AIRSHIP')
-- AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 )
-- AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);
------------------------
-- UnitPromotions
------------------------
--UPDATE UnitPromotions
--SET Help = 'TXT_KEY_PROMOTION_JFD_JUNGLE_IMPASSABLE_HELP_CBP'
--WHERE Type = 'PROMOTION_JFD_JUNGLE_IMPASSABLE'
--AND EXISTS (SELECT * FROM COMMUNITY WHERE Type = 'COMMUNITY_CORE_BALANCE_LUXURY_HAPPINESS' AND Value = 1);
------------------------
-- Unit_ClassUpgrades
------------------------
DELETE FROM Unit_ClassUpgrades WHERE UnitClassType IN ('UNITCLASS_EXPLORER', 'UNITCLASS_ADVENTURER')
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);
------------------------
-- Unit_FreePromotions
------------------------
INSERT INTO Unit_FreePromotions
		(UnitType,	PromotionType)
SELECT	Type,		'PROMOTION_RECON_EXPERIENCE'
FROM Units WHERE Class IN ('UNITCLASS_JFD_EXPLORER', 'UNITCLASS_JFD_ADVENTURER', 'UNITCLASS_JFD_AIRSHIP', 'UNITCLASS_JFD_GREAT_SCOUT', 'UNITCLASS_JFD_GREAT_EXPLORER', 'UNITCLASS_JFD_GREAT_ADVENTURER', 'UNITCLASS_JFD_GREAT_AIRSHIP')
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);
------------------------
-- Resources
------------------------
UPDATE Resources 
SET IsMonopoly = 1, Help = 'TXT_KEY_' || Type || '_HELP_MONOPOLY'
WHERE Type IN ('RESOURCE_JFD_OBSIDIAN', 'RESOURCE_JFD_OPIUM', 'RESOURCE_JFD_SAFFRON', 'RESOURCE_JFD_VANILLA', 'RESOURCE_JFD_MANUSCRIPTS')
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1);

--Luxury Resources
UPDATE Resources 
SET Happiness = 1
WHERE Type IN ('RESOURCE_JFD_OBSIDIAN', 'RESOURCE_JFD_OPIUM', 'RESOURCE_JFD_SAFFRON', 'RESOURCE_JFD_VANILLA')
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1)
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type = 'COMMUNITY_CORE_BALANCE_LUXURY_HAPPINESS' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1);

--Bonus Resources
UPDATE Resources
SET TechReveal = 'TECH_MASONRY'
WHERE Type = 'RESOURCE_JFD_OAK'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1)
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type = 'COMMUNITY_CORE_BALANCE_RESOURCE_REVEAL' AND Value IN (1,3))
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_BONUS' AND Value = 1);

UPDATE Resources
SET TechReveal = 'TECH_HORSEBACK_RIDING'
WHERE Type IN ('RESOURCE_JFD_GINGER', 'RESOURCE_JFD_CEDAR')
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1)
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type = 'COMMUNITY_CORE_BALANCE_RESOURCE_REVEAL' AND Value IN (1,3))
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_BONUS' AND Value = 1);

UPDATE Resources
SET TechReveal = 'TECH_CALENDAR'
WHERE Type = 'RESOURCE_JFD_LOTUS'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1)
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type = 'COMMUNITY_CORE_BALANCE_RESOURCE_REVEAL' AND Value IN (1,3))
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_BONUS' AND Value = 1);

--Obsidian
UPDATE Resources
SET MonopolyAttackBonus = 10
WHERE Type = 'RESOURCE_JFD_OBSIDIAN'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1)
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type = 'COMMUNITY_CORE_BALANCE_RESOURCE_REVEAL' AND Value IN (2,3));

--Vanilla
UPDATE Resources
SET MonopolyHappiness = 5
WHERE Type = 'RESOURCE_JFD_VANILLA'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1)
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type = 'COMMUNITY_CORE_BALANCE_RESOURCE_REVEAL' AND Value IN (2,3));

INSERT INTO Resource_YieldChangeFromMonopoly 
		(ResourceType, 		YieldType, 		Yield)
SELECT	Type, 				'YIELD_GOLD',	2
FROM Resources WHERE Type IN ('RESOURCE_JFD_OPIUM', 'RESOURCE_JFD_SAFFRON')
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1);

INSERT INTO Resource_YieldChangeFromMonopoly 
		(ResourceType, 		YieldType, 		Yield)
SELECT	Type, 				'YIELD_FAITH',	2
FROM Resources WHERE Type IN ('RESOURCE_JFD_OPIUM', 'RESOURCE_JFD_SAFFRON')
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1);

INSERT INTO Resource_CityYieldModFromMonopoly 
		(ResourceType, 		YieldType, 			Yield)
SELECT	Type, 				'YIELD_CULTURE',	5
FROM Resources WHERE Type IN ('RESOURCE_JFD_MANUSCRIPTS')
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1);

INSERT INTO Resource_CityYieldModFromMonopoly 
		(ResourceType, 		YieldType, 			Yield)
SELECT	Type, 				'YIELD_FAITH',		5
FROM Resources WHERE Type IN ('RESOURCE_JFD_MANUSCRIPTS')
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1);

--INSERT INTO Improvement_ResourceTypes 
--		(ImprovementType, 		ResourceType)
--SELECT	'IMPROVEMENT_KASBAH', 	Type
--FROM Resources WHERE Type IN ('RESOURCE_JFD_OAK', 'RESOURCE_JFD_SULFUR', 'RESOURCE_JFD_GINGER', 'RESOURCE_JFD_RUBBER', 'RESOURCE_JFD_CEDAR')
--AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1)
--AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_BONUS' AND Value = 1);
--
--INSERT INTO Improvement_ResourceTypes 
--		(ImprovementType, 		ResourceType)
--SELECT	'IMPROVEMENT_KASBAH', 	Type
--FROM Resources WHERE Type IN ('RESOURCE_JFD_OBSIDIAN', 'RESOURCE_JFD_OPIUM', 'RESOURCE_JFD_VANILLA', 'RESOURCE_JFD_SAFFRON')
--AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1)
--AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1);
------------------------
-- Resource_YieldChanges
------------------------
DELETE FROM Resource_YieldChanges WHERE ResourceType = 'RESOURCE_JFD_SAFFRON'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);
INSERT INTO Resource_YieldChanges 	
		(ResourceType, 			 YieldType, 	Yield)
SELECT	'RESOURCE_JFD_SAFFRON',	 YieldType, 	Yield
FROM Resource_YieldChanges WHERE ResourceType = 'RESOURCE_INCENSE'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);

UPDATE Resource_YieldChanges
SET YieldType = 'YIELD_GOLD'
WHERE ResourceType = 'RESOURCE_JFD_SAFFRON'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);
------------------------
-- Improvement_ResourceType_Yields
------------------------
DELETE FROM Improvement_ResourceType_Yields WHERE ResourceType = 'RESOURCE_JFD_SAFFRON'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);
INSERT INTO Improvement_ResourceType_Yields 	
		(ResourceType, 			ImprovementType,	YieldType, 	Yield)
SELECT	'RESOURCE_JFD_SAFFRON',	ImprovementType,	YieldType, 	Yield
FROM Improvement_ResourceType_Yields WHERE ResourceType = 'RESOURCE_INCENSE'
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_RESOURCE_ADDITIONS_LUXURY' AND Value = 1)
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_COMMUNITY_BALANCE_PATCH' AND Value = 1);
--==========================================================================================================================
-- HULGAR INDUSTRIAL PACK
--==========================================================================================================================
-- Units
------------------------
UPDATE Units
SET PrereqTech = NULL, Cost = -1, ShowInPedia = 0
WHERE Type IN ('UNIT_EXPLORATEUR');

UPDATE Units 
SET PrereqTech = 'TECH_CARTOGRAPHY'
WHERE Type = 'UNIT_JFD_GREAT_SCOUT'
AND EXISTS (SELECT * FROM Technologies WHERE Type = 'TECH_CARTOGRAPHY');
--==========================================================================================================================
-- POUAKAI ENLIGHTENMENT ERA
--==========================================================================================================================
-- Buildings
------------------------
UPDATE Buildings 
SET PrereqTech = 'TECH_EE_EXPLORATION'
WHERE Type IN ('BUILDING_JFD_BELEM_TOWER')
AND EXISTS (SELECT * FROM Technologies WHERE Type = 'TECH_EE_EXPLORATION')
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_WONDER_ADDITIONS_BELEM_TOWER' AND Value = 1);
------------------------
-- Policies
------------------------
UPDATE Policies
SET Help = 'TXT_KEY_POLICY_JFD_MARITIME_INFRASTRUCTURE_HELP_EE'
WHERE Type = 'POLICY_MARITIME_INFRASTRUCTURE'
AND EXISTS (SELECT * FROM Technologies WHERE Type = 'TECH_EE_EXPLORATION')
AND EXISTS (SELECT * FROM JFD_GlobalUserSettings WHERE Type = 'JFD_EXCE_EXPLORATION_POLICY_CHANGES' AND Value = 1);
------------------------
-- Units
------------------------
UPDATE Units
SET PrereqTech = NULL, Cost = -1, ShowInPedia = 0, FaithCost = 0, CannotBeMerc = 1
WHERE Type IN ('UNIT_EE_EXPLORER', 'UNIT_EE_SURVEYOR');

UPDATE Units 
SET PrereqTech = 'TECH_EE_EXPLORATION'
WHERE Type IN ('UNIT_JFD_GREAT_EXPLORER', 'UNIT_JFD_EXPLORER')
AND EXISTS (SELECT * FROM Technologies WHERE Type = 'TECH_EE_EXPLORATION');

UPDATE Units 
SET PrereqTech = 'TECH_EE_NATURAL_HISTORY'
WHERE Type IN ('UNIT_JFD_GREAT_ADVENTURER', 'UNIT_JFD_ADVENTURER')
AND EXISTS (SELECT * FROM Technologies WHERE Type = 'TECH_EE_NATURAL_HISTORY');
------------------------
-- Unit_ClassUpgrades
------------------------
DELETE FROM Unit_ClassUpgrades WHERE UnitClassType IN ('UNITCLASS_EE_EXPLORER', 'UNITCLASS_EE_SURVEYOR');
--==========================================================================================================================
--==========================================================================================================================